=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::AiApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# ai_suggest_api
#
# 
#
# @param AiSuggestionRequest $ai_suggestion_request  (required)
{
    my $params = {
    'ai_suggestion_request' => {
        data_type => 'AiSuggestionRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'ai_suggest_api' } = {
        summary => '',
        params => $params,
        returns => 'AiSuggestion',
        };
}
# @return AiSuggestion
#
sub ai_suggest_api {
    my ($self, %args) = @_;

    # verify the required parameter 'ai_suggestion_request' is set
    unless (exists $args{'ai_suggestion_request'}) {
      croak("Missing the required parameter 'ai_suggestion_request' when calling ai_suggest_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/support/ai/suggest';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'ai_suggestion_request'}) {
        $_body_data = $args{'ai_suggestion_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AiSuggestion', $response);
    return $_response_object;
}

#
# create_worker_api
#
# 
#
# @param AiConfigDto $ai_config_dto  (required)
{
    my $params = {
    'ai_config_dto' => {
        data_type => 'AiConfigDto',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_worker_api' } = {
        summary => '',
        params => $params,
        returns => 'AiWorkerConfig',
        };
}
# @return AiWorkerConfig
#
sub create_worker_api {
    my ($self, %args) = @_;

    # verify the required parameter 'ai_config_dto' is set
    unless (exists $args{'ai_config_dto'}) {
      croak("Missing the required parameter 'ai_config_dto' when calling create_worker_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/support/ai/workers';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'ai_config_dto'}) {
        $_body_data = $args{'ai_config_dto'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AiWorkerConfig', $response);
    return $_response_object;
}

#
# list_workers_api
#
# 
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'list_workers_api' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[AiWorkerConfig]',
        };
}
# @return ARRAY[AiWorkerConfig]
#
sub list_workers_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/support/ai/workers';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[AiWorkerConfig]', $response);
    return $_response_object;
}

#
# run_worker_api
#
# 
#
# @param string $worker_id  (required)
# @param AiSuggestionRequest $ai_suggestion_request  (required)
{
    my $params = {
    'worker_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'ai_suggestion_request' => {
        data_type => 'AiSuggestionRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'run_worker_api' } = {
        summary => '',
        params => $params,
        returns => 'AiSuggestion',
        };
}
# @return AiSuggestion
#
sub run_worker_api {
    my ($self, %args) = @_;

    # verify the required parameter 'worker_id' is set
    unless (exists $args{'worker_id'}) {
      croak("Missing the required parameter 'worker_id' when calling run_worker_api");
    }

    # verify the required parameter 'ai_suggestion_request' is set
    unless (exists $args{'ai_suggestion_request'}) {
      croak("Missing the required parameter 'ai_suggestion_request' when calling run_worker_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/support/ai/workers/{worker_id}/run';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'worker_id'}) {
        my $_base_variable = "{" . "worker_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'worker_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'ai_suggestion_request'}) {
        $_body_data = $args{'ai_suggestion_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AiSuggestion', $response);
    return $_response_object;
}

1;
