=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::AuthApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# accept_invite
#
# Accept an invite: create the account (or reuse an existing one) and join the inviting tenant. The invite token proves control of the mailbox.
#
# @param AcceptInviteRequest $accept_invite_request  (required)
{
    my $params = {
    'accept_invite_request' => {
        data_type => 'AcceptInviteRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'accept_invite' } = {
        summary => 'Accept an invite: create the account (or reuse an existing one) and join the inviting tenant. The invite token proves control of the mailbox.',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub accept_invite {
    my ($self, %args) = @_;

    # verify the required parameter 'accept_invite_request' is set
    unless (exists $args{'accept_invite_request'}) {
      croak("Missing the required parameter 'accept_invite_request' when calling accept_invite");
    }

    # parse inputs
    my $_resource_path = '/auth/accept-invite';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'accept_invite_request'}) {
        $_body_data = $args{'accept_invite_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# forgot_password
#
# Send a password reset email to the user
#
# @param ForgotPasswordRequest $forgot_password_request  (required)
{
    my $params = {
    'forgot_password_request' => {
        data_type => 'ForgotPasswordRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'forgot_password' } = {
        summary => 'Send a password reset email to the user',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub forgot_password {
    my ($self, %args) = @_;

    # verify the required parameter 'forgot_password_request' is set
    unless (exists $args{'forgot_password_request'}) {
      croak("Missing the required parameter 'forgot_password_request' when calling forgot_password");
    }

    # parse inputs
    my $_resource_path = '/auth/forgot-password';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'forgot_password_request'}) {
        $_body_data = $args{'forgot_password_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# login
#
# Authenticate a user with email + password (optional TOTP)
#
# @param LoginRequest $login_request  (required)
{
    my $params = {
    'login_request' => {
        data_type => 'LoginRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'login' } = {
        summary => 'Authenticate a user with email + password (optional TOTP)',
        params => $params,
        returns => 'AuthResponse',
        };
}
# @return AuthResponse
#
sub login {
    my ($self, %args) = @_;

    # verify the required parameter 'login_request' is set
    unless (exists $args{'login_request'}) {
      croak("Missing the required parameter 'login_request' when calling login");
    }

    # parse inputs
    my $_resource_path = '/auth/login';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'login_request'}) {
        $_body_data = $args{'login_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AuthResponse', $response);
    return $_response_object;
}

#
# logout
#
# Log out the current user (kills the assay session)
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'logout' } = {
        summary => 'Log out the current user (kills the assay session)',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub logout {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/auth/logout';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# magic_link_login
#
# Request a magic link login (sends an email with a one-time link)
#
# @param MagicLinkRequest $magic_link_request  (required)
{
    my $params = {
    'magic_link_request' => {
        data_type => 'MagicLinkRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'magic_link_login' } = {
        summary => 'Request a magic link login (sends an email with a one-time link)',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub magic_link_login {
    my ($self, %args) = @_;

    # verify the required parameter 'magic_link_request' is set
    unless (exists $args{'magic_link_request'}) {
      croak("Missing the required parameter 'magic_link_request' when calling magic_link_login");
    }

    # parse inputs
    my $_resource_path = '/auth/magic-link';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'magic_link_request'}) {
        $_body_data = $args{'magic_link_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# magic_link_verify
#
# Verify a magic link token and log the user in
#
# @param MagicLinkVerifyRequest $magic_link_verify_request  (required)
{
    my $params = {
    'magic_link_verify_request' => {
        data_type => 'MagicLinkVerifyRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'magic_link_verify' } = {
        summary => 'Verify a magic link token and log the user in',
        params => $params,
        returns => 'AuthResponse',
        };
}
# @return AuthResponse
#
sub magic_link_verify {
    my ($self, %args) = @_;

    # verify the required parameter 'magic_link_verify_request' is set
    unless (exists $args{'magic_link_verify_request'}) {
      croak("Missing the required parameter 'magic_link_verify_request' when calling magic_link_verify");
    }

    # parse inputs
    my $_resource_path = '/auth/magic-link/verify';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'magic_link_verify_request'}) {
        $_body_data = $args{'magic_link_verify_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AuthResponse', $response);
    return $_response_object;
}

#
# register
#
# Register a new user account
#
# @param RegisterRequest $register_request  (required)
{
    my $params = {
    'register_request' => {
        data_type => 'RegisterRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'register' } = {
        summary => 'Register a new user account',
        params => $params,
        returns => 'AuthResponse',
        };
}
# @return AuthResponse
#
sub register {
    my ($self, %args) = @_;

    # verify the required parameter 'register_request' is set
    unless (exists $args{'register_request'}) {
      croak("Missing the required parameter 'register_request' when calling register");
    }

    # parse inputs
    my $_resource_path = '/auth/register';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'register_request'}) {
        $_body_data = $args{'register_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AuthResponse', $response);
    return $_response_object;
}

#
# reset_password
#
# Reset the user's password using a reset token
#
# @param ResetPasswordRequest $reset_password_request  (required)
{
    my $params = {
    'reset_password_request' => {
        data_type => 'ResetPasswordRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'reset_password' } = {
        summary => 'Reset the user&#39;s password using a reset token',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub reset_password {
    my ($self, %args) = @_;

    # verify the required parameter 'reset_password_request' is set
    unless (exists $args{'reset_password_request'}) {
      croak("Missing the required parameter 'reset_password_request' when calling reset_password");
    }

    # parse inputs
    my $_resource_path = '/auth/reset-password';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'reset_password_request'}) {
        $_body_data = $args{'reset_password_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# totp_enable
#
# Enable TOTP two-factor authentication by verifying a code
#
# @param TotpEnableRequest $totp_enable_request  (required)
{
    my $params = {
    'totp_enable_request' => {
        data_type => 'TotpEnableRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'totp_enable' } = {
        summary => 'Enable TOTP two-factor authentication by verifying a code',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub totp_enable {
    my ($self, %args) = @_;

    # verify the required parameter 'totp_enable_request' is set
    unless (exists $args{'totp_enable_request'}) {
      croak("Missing the required parameter 'totp_enable_request' when calling totp_enable");
    }

    # parse inputs
    my $_resource_path = '/auth/totp/enable';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'totp_enable_request'}) {
        $_body_data = $args{'totp_enable_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# totp_setup
#
# Set up TOTP two-factor authentication (generates secret + backup codes)
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'totp_setup' } = {
        summary => 'Set up TOTP two-factor authentication (generates secret + backup codes)',
        params => $params,
        returns => 'TotpSetupResponse',
        };
}
# @return TotpSetupResponse
#
sub totp_setup {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/auth/totp/setup';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TotpSetupResponse', $response);
    return $_response_object;
}

#
# verify_email
#
# Verify a user's email address using a verification token
#
# @param VerifyEmailRequest $verify_email_request  (required)
{
    my $params = {
    'verify_email_request' => {
        data_type => 'VerifyEmailRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'verify_email' } = {
        summary => 'Verify a user&#39;s email address using a verification token',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub verify_email {
    my ($self, %args) = @_;

    # verify the required parameter 'verify_email_request' is set
    unless (exists $args{'verify_email_request'}) {
      croak("Missing the required parameter 'verify_email_request' when calling verify_email");
    }

    # parse inputs
    my $_resource_path = '/auth/verify-email';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept();
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'verify_email_request'}) {
        $_body_data = $args{'verify_email_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
