=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::BomApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_bom
#
# 
#
# @param BomCreate $bom_create  (required)
{
    my $params = {
    'bom_create' => {
        data_type => 'BomCreate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_bom' } = {
        summary => '',
        params => $params,
        returns => 'Bom',
        };
}
# @return Bom
#
sub create_bom {
    my ($self, %args) = @_;

    # verify the required parameter 'bom_create' is set
    unless (exists $args{'bom_create'}) {
      croak("Missing the required parameter 'bom_create' when calling create_bom");
    }

    # parse inputs
    my $_resource_path = '/api/v1/boms';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'bom_create'}) {
        $_body_data = $args{'bom_create'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Bom', $response);
    return $_response_object;
}

#
# delete_bom
#
# 
#
# @param string $bom_id  (required)
{
    my $params = {
    'bom_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_bom' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_bom {
    my ($self, %args) = @_;

    # verify the required parameter 'bom_id' is set
    unless (exists $args{'bom_id'}) {
      croak("Missing the required parameter 'bom_id' when calling delete_bom");
    }

    # parse inputs
    my $_resource_path = '/api/v1/boms/{bom_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'bom_id'}) {
        my $_base_variable = "{" . "bom_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'bom_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_bom
#
# 
#
# @param string $bom_id  (required)
{
    my $params = {
    'bom_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_bom' } = {
        summary => '',
        params => $params,
        returns => 'Bom',
        };
}
# @return Bom
#
sub get_bom {
    my ($self, %args) = @_;

    # verify the required parameter 'bom_id' is set
    unless (exists $args{'bom_id'}) {
      croak("Missing the required parameter 'bom_id' when calling get_bom");
    }

    # parse inputs
    my $_resource_path = '/api/v1/boms/{bom_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'bom_id'}) {
        my $_base_variable = "{" . "bom_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'bom_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Bom', $response);
    return $_response_object;
}

#
# list_boms
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $search  (optional)
# @param string $product_id Filter by finished product id. (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'search' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'product_id' => {
        data_type => 'string',
        description => 'Filter by finished product id.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_boms' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[Bom]',
        };
}
# @return ARRAY[Bom]
#
sub list_boms {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/boms/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'search'}) {
        $query_params->{'search'} = $self->{api_client}->to_query_value($args{'search'});
    }

    # query params
    if ( exists $args{'product_id'}) {
        $query_params->{'productId'} = $self->{api_client}->to_query_value($args{'product_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Bom]', $response);
    return $_response_object;
}

#
# update_bom
#
# 
#
# @param string $bom_id  (required)
# @param BomUpdate $bom_update  (required)
{
    my $params = {
    'bom_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'bom_update' => {
        data_type => 'BomUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_bom' } = {
        summary => '',
        params => $params,
        returns => 'Bom',
        };
}
# @return Bom
#
sub update_bom {
    my ($self, %args) = @_;

    # verify the required parameter 'bom_id' is set
    unless (exists $args{'bom_id'}) {
      croak("Missing the required parameter 'bom_id' when calling update_bom");
    }

    # verify the required parameter 'bom_update' is set
    unless (exists $args{'bom_update'}) {
      croak("Missing the required parameter 'bom_update' when calling update_bom");
    }

    # parse inputs
    my $_resource_path = '/api/v1/boms/{bom_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'bom_id'}) {
        my $_base_variable = "{" . "bom_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'bom_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'bom_update'}) {
        $_body_data = $args{'bom_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Bom', $response);
    return $_response_object;
}

1;
