=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::DeliveryDateApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_delivery_date
#
# 
#
# @param DeliveryDateCreate $delivery_date_create  (required)
{
    my $params = {
    'delivery_date_create' => {
        data_type => 'DeliveryDateCreate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_delivery_date' } = {
        summary => '',
        params => $params,
        returns => 'DeliveryDate',
        };
}
# @return DeliveryDate
#
sub create_delivery_date {
    my ($self, %args) = @_;

    # verify the required parameter 'delivery_date_create' is set
    unless (exists $args{'delivery_date_create'}) {
      croak("Missing the required parameter 'delivery_date_create' when calling create_delivery_date");
    }

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'delivery_date_create'}) {
        $_body_data = $args{'delivery_date_create'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('DeliveryDate', $response);
    return $_response_object;
}

#
# delete_delivery_date
#
# 
#
# @param string $delivery_date_id  (required)
{
    my $params = {
    'delivery_date_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_delivery_date' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_delivery_date {
    my ($self, %args) = @_;

    # verify the required parameter 'delivery_date_id' is set
    unless (exists $args{'delivery_date_id'}) {
      croak("Missing the required parameter 'delivery_date_id' when calling delete_delivery_date");
    }

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/{delivery_date_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'delivery_date_id'}) {
        my $_base_variable = "{" . "delivery_date_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'delivery_date_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_delivery_date
#
# 
#
# @param string $delivery_date_id  (required)
{
    my $params = {
    'delivery_date_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_delivery_date' } = {
        summary => '',
        params => $params,
        returns => 'DeliveryDate',
        };
}
# @return DeliveryDate
#
sub get_delivery_date {
    my ($self, %args) = @_;

    # verify the required parameter 'delivery_date_id' is set
    unless (exists $args{'delivery_date_id'}) {
      croak("Missing the required parameter 'delivery_date_id' when calling get_delivery_date");
    }

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/{delivery_date_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'delivery_date_id'}) {
        my $_base_variable = "{" . "delivery_date_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'delivery_date_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('DeliveryDate', $response);
    return $_response_object;
}

#
# get_delivery_performance
#
# On-time performance summary: how many promised delivery dates were met within a period.
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $order_number  (optional)
# @param string $status  (optional)
# @param DATE $from Only dates on or after this date. (optional)
# @param DATE $to Only dates on or before this date. (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'status' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'from' => {
        data_type => 'DATE',
        description => 'Only dates on or after this date.',
        required => '0',
    },
    'to' => {
        data_type => 'DATE',
        description => 'Only dates on or before this date.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_delivery_performance' } = {
        summary => 'On-time performance summary: how many promised delivery dates were met within a period.',
        params => $params,
        returns => 'object',
        };
}
# @return object
#
sub get_delivery_performance {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/performance';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'order_number'}) {
        $query_params->{'orderNumber'} = $self->{api_client}->to_query_value($args{'order_number'});
    }

    # query params
    if ( exists $args{'status'}) {
        $query_params->{'status'} = $self->{api_client}->to_query_value($args{'status'});
    }

    # query params
    if ( exists $args{'from'}) {
        $query_params->{'from'} = $self->{api_client}->to_query_value($args{'from'});
    }

    # query params
    if ( exists $args{'to'}) {
        $query_params->{'to'} = $self->{api_client}->to_query_value($args{'to'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('object', $response);
    return $_response_object;
}

#
# list_delivery_dates
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $order_number  (optional)
# @param string $status  (optional)
# @param DATE $from Only dates on or after this date. (optional)
# @param DATE $to Only dates on or before this date. (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'status' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'from' => {
        data_type => 'DATE',
        description => 'Only dates on or after this date.',
        required => '0',
    },
    'to' => {
        data_type => 'DATE',
        description => 'Only dates on or before this date.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_delivery_dates' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[DeliveryDate]',
        };
}
# @return ARRAY[DeliveryDate]
#
sub list_delivery_dates {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'pageSize'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'order_number'}) {
        $query_params->{'orderNumber'} = $self->{api_client}->to_query_value($args{'order_number'});
    }

    # query params
    if ( exists $args{'status'}) {
        $query_params->{'status'} = $self->{api_client}->to_query_value($args{'status'});
    }

    # query params
    if ( exists $args{'from'}) {
        $query_params->{'from'} = $self->{api_client}->to_query_value($args{'from'});
    }

    # query params
    if ( exists $args{'to'}) {
        $query_params->{'to'} = $self->{api_client}->to_query_value($args{'to'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[DeliveryDate]', $response);
    return $_response_object;
}

#
# update_delivery_date
#
# 
#
# @param string $delivery_date_id  (required)
# @param object $body  (required)
{
    my $params = {
    'delivery_date_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_delivery_date' } = {
        summary => '',
        params => $params,
        returns => 'DeliveryDate',
        };
}
# @return DeliveryDate
#
sub update_delivery_date {
    my ($self, %args) = @_;

    # verify the required parameter 'delivery_date_id' is set
    unless (exists $args{'delivery_date_id'}) {
      croak("Missing the required parameter 'delivery_date_id' when calling update_delivery_date");
    }

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/{delivery_date_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'delivery_date_id'}) {
        my $_base_variable = "{" . "delivery_date_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'delivery_date_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('DeliveryDate', $response);
    return $_response_object;
}

#
# update_delivery_date_status
#
# 
#
# @param string $delivery_date_id  (required)
# @param DeliveryDateStatusUpdate $delivery_date_status_update  (required)
{
    my $params = {
    'delivery_date_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'delivery_date_status_update' => {
        data_type => 'DeliveryDateStatusUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_delivery_date_status' } = {
        summary => '',
        params => $params,
        returns => 'DeliveryDate',
        };
}
# @return DeliveryDate
#
sub update_delivery_date_status {
    my ($self, %args) = @_;

    # verify the required parameter 'delivery_date_id' is set
    unless (exists $args{'delivery_date_id'}) {
      croak("Missing the required parameter 'delivery_date_id' when calling update_delivery_date_status");
    }

    # verify the required parameter 'delivery_date_status_update' is set
    unless (exists $args{'delivery_date_status_update'}) {
      croak("Missing the required parameter 'delivery_date_status_update' when calling update_delivery_date_status");
    }

    # parse inputs
    my $_resource_path = '/api/v1/delivery-dates/{delivery_date_id}/status';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'delivery_date_id'}) {
        my $_base_variable = "{" . "delivery_date_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'delivery_date_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'delivery_date_status_update'}) {
        $_body_data = $args{'delivery_date_status_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('DeliveryDate', $response);
    return $_response_object;
}

1;
