=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::EbilanzApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# ebilanz_report_api
#
# 
#
# @param int $year  (optional)
# @param string $date_from  (optional)
# @param string $date_to  (optional)
{
    my $params = {
    'year' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'date_from' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'date_to' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'ebilanz_report_api' } = {
        summary => '',
        params => $params,
        returns => 'EBilanzReport',
        };
}
# @return EBilanzReport
#
sub ebilanz_report_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/ebilanz';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    # query params
    if ( exists $args{'date_from'}) {
        $query_params->{'date_from'} = $self->{api_client}->to_query_value($args{'date_from'});
    }

    # query params
    if ( exists $args{'date_to'}) {
        $query_params->{'date_to'} = $self->{api_client}->to_query_value($args{'date_to'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EBilanzReport', $response);
    return $_response_object;
}

#
# ebilanz_xbrl_export_api
#
# 
#
# @param int $year  (optional)
# @param string $date_from  (optional)
# @param string $date_to  (optional)
{
    my $params = {
    'year' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'date_from' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'date_to' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'ebilanz_xbrl_export_api' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub ebilanz_xbrl_export_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/ebilanz/xbrl';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/xml');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    # query params
    if ( exists $args{'date_from'}) {
        $query_params->{'date_from'} = $self->{api_client}->to_query_value($args{'date_from'});
    }

    # query params
    if ( exists $args{'date_to'}) {
        $query_params->{'date_to'} = $self->{api_client}->to_query_value($args{'date_to'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
