=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::EmissionsApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_emission_entry_api
#
# 
#
# @param CreateEmissionEntry $create_emission_entry  (required)
{
    my $params = {
    'create_emission_entry' => {
        data_type => 'CreateEmissionEntry',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_emission_entry_api' } = {
        summary => '',
        params => $params,
        returns => 'EmissionEntry',
        };
}
# @return EmissionEntry
#
sub create_emission_entry_api {
    my ($self, %args) = @_;

    # verify the required parameter 'create_emission_entry' is set
    unless (exists $args{'create_emission_entry'}) {
      croak("Missing the required parameter 'create_emission_entry' when calling create_emission_entry_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/entries';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'create_emission_entry'}) {
        $_body_data = $args{'create_emission_entry'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EmissionEntry', $response);
    return $_response_object;
}

#
# create_emission_target_api
#
# 
#
# @param CreateEmissionTarget $create_emission_target  (required)
{
    my $params = {
    'create_emission_target' => {
        data_type => 'CreateEmissionTarget',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_emission_target_api' } = {
        summary => '',
        params => $params,
        returns => 'EmissionTarget',
        };
}
# @return EmissionTarget
#
sub create_emission_target_api {
    my ($self, %args) = @_;

    # verify the required parameter 'create_emission_target' is set
    unless (exists $args{'create_emission_target'}) {
      croak("Missing the required parameter 'create_emission_target' when calling create_emission_target_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/targets';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'create_emission_target'}) {
        $_body_data = $args{'create_emission_target'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EmissionTarget', $response);
    return $_response_object;
}

#
# delete_emission_entry_api
#
# 
#
# @param string $id  (required)
{
    my $params = {
    'id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_emission_entry_api' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_emission_entry_api {
    my ($self, %args) = @_;

    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling delete_emission_entry_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/entries/{id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# delete_emission_target_api
#
# 
#
# @param string $id  (required)
{
    my $params = {
    'id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_emission_target_api' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_emission_target_api {
    my ($self, %args) = @_;

    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling delete_emission_target_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/targets/{id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# emissions_entries_api
#
# 
#
# @param int $year  (required)
{
    my $params = {
    'year' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'emissions_entries_api' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[EmissionEntry]',
        };
}
# @return ARRAY[EmissionEntry]
#
sub emissions_entries_api {
    my ($self, %args) = @_;

    # verify the required parameter 'year' is set
    unless (exists $args{'year'}) {
      croak("Missing the required parameter 'year' when calling emissions_entries_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/entries';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[EmissionEntry]', $response);
    return $_response_object;
}

#
# emissions_export_api
#
# 
#
# @param int $year  (required)
{
    my $params = {
    'year' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'emissions_export_api' } = {
        summary => '',
        params => $params,
        returns => 'EmissionsExportResponse',
        };
}
# @return EmissionsExportResponse
#
sub emissions_export_api {
    my ($self, %args) = @_;

    # verify the required parameter 'year' is set
    unless (exists $args{'year'}) {
      croak("Missing the required parameter 'year' when calling emissions_export_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/export';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EmissionsExportResponse', $response);
    return $_response_object;
}

#
# emissions_factors_api
#
# 
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'emissions_factors_api' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[EmissionFactorResponse]',
        };
}
# @return ARRAY[EmissionFactorResponse]
#
sub emissions_factors_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/factors';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[EmissionFactorResponse]', $response);
    return $_response_object;
}

#
# emissions_report_api
#
# 
#
# @param int $year  (required)
{
    my $params = {
    'year' => {
        data_type => 'int',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'emissions_report_api' } = {
        summary => '',
        params => $params,
        returns => 'EmissionsReport',
        };
}
# @return EmissionsReport
#
sub emissions_report_api {
    my ($self, %args) = @_;

    # verify the required parameter 'year' is set
    unless (exists $args{'year'}) {
      croak("Missing the required parameter 'year' when calling emissions_report_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/report';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'year'}) {
        $query_params->{'year'} = $self->{api_client}->to_query_value($args{'year'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('EmissionsReport', $response);
    return $_response_object;
}

#
# emissions_targets_api
#
# 
#
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'emissions_targets_api' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[EmissionTarget]',
        };
}
# @return ARRAY[EmissionTarget]
#
sub emissions_targets_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/emissions/targets';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[EmissionTarget]', $response);
    return $_response_object;
}

1;
