=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::FristenApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# fristen_api
#
# 
#
# @param string $bundesland  (optional)
# @param string $voranmeldungsrhythmus  (optional)
# @param boolean $dauerfristverlaengerung  (optional)
# @param boolean $est_aktiv  (optional)
# @param boolean $gewst_aktiv  (optional)
# @param int $monate  (optional)
{
    my $params = {
    'bundesland' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'voranmeldungsrhythmus' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'dauerfristverlaengerung' => {
        data_type => 'boolean',
        description => '',
        required => '0',
    },
    'est_aktiv' => {
        data_type => 'boolean',
        description => '',
        required => '0',
    },
    'gewst_aktiv' => {
        data_type => 'boolean',
        description => '',
        required => '0',
    },
    'monate' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'fristen_api' } = {
        summary => '',
        params => $params,
        returns => 'FristenErgebnis',
        };
}
# @return FristenErgebnis
#
sub fristen_api {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/bookkeeping/fristen';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'bundesland'}) {
        $query_params->{'bundesland'} = $self->{api_client}->to_query_value($args{'bundesland'});
    }

    # query params
    if ( exists $args{'voranmeldungsrhythmus'}) {
        $query_params->{'voranmeldungsrhythmus'} = $self->{api_client}->to_query_value($args{'voranmeldungsrhythmus'});
    }

    # query params
    if ( exists $args{'dauerfristverlaengerung'}) {
        $query_params->{'dauerfristverlaengerung'} = $self->{api_client}->to_query_value($args{'dauerfristverlaengerung'});
    }

    # query params
    if ( exists $args{'est_aktiv'}) {
        $query_params->{'est_aktiv'} = $self->{api_client}->to_query_value($args{'est_aktiv'});
    }

    # query params
    if ( exists $args{'gewst_aktiv'}) {
        $query_params->{'gewst_aktiv'} = $self->{api_client}->to_query_value($args{'gewst_aktiv'});
    }

    # query params
    if ( exists $args{'monate'}) {
        $query_params->{'monate'} = $self->{api_client}->to_query_value($args{'monate'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('FristenErgebnis', $response);
    return $_response_object;
}

1;
