=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::GenerateQrcodeApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# generate_qrcode_api
#
# 
#
# @param string $iban  (required)
# @param string $id  (required)
# @param string $holder_name  (optional)
# @param string $bic  (optional)
# @param string $amount  (optional)
# @param string $reference  (optional)
# @param string $purpose  (optional)
{
    my $params = {
    'iban' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'holder_name' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'bic' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'amount' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'reference' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'purpose' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'generate_qrcode_api' } = {
        summary => '',
        params => $params,
        returns => 'QRCodeResponse',
        };
}
# @return QRCodeResponse
#
sub generate_qrcode_api {
    my ($self, %args) = @_;

    # verify the required parameter 'iban' is set
    unless (exists $args{'iban'}) {
      croak("Missing the required parameter 'iban' when calling generate_qrcode_api");
    }

    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling generate_qrcode_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/invoices/{id}/qrcode';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'iban'}) {
        $query_params->{'iban'} = $self->{api_client}->to_query_value($args{'iban'});
    }

    # query params
    if ( exists $args{'holder_name'}) {
        $query_params->{'holder_name'} = $self->{api_client}->to_query_value($args{'holder_name'});
    }

    # query params
    if ( exists $args{'bic'}) {
        $query_params->{'bic'} = $self->{api_client}->to_query_value($args{'bic'});
    }

    # query params
    if ( exists $args{'amount'}) {
        $query_params->{'amount'} = $self->{api_client}->to_query_value($args{'amount'});
    }

    # query params
    if ( exists $args{'reference'}) {
        $query_params->{'reference'} = $self->{api_client}->to_query_value($args{'reference'});
    }

    # query params
    if ( exists $args{'purpose'}) {
        $query_params->{'purpose'} = $self->{api_client}->to_query_value($args{'purpose'});
    }

    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('QRCodeResponse', $response);
    return $_response_object;
}

1;
