=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::GoodsReceiptApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_goods_receipt
#
# 
#
# @param GoodsReceipt $goods_receipt  (required)
{
    my $params = {
    'goods_receipt' => {
        data_type => 'GoodsReceipt',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_goods_receipt' } = {
        summary => '',
        params => $params,
        returns => 'GoodsReceipt',
        };
}
# @return GoodsReceipt
#
sub create_goods_receipt {
    my ($self, %args) = @_;

    # verify the required parameter 'goods_receipt' is set
    unless (exists $args{'goods_receipt'}) {
      croak("Missing the required parameter 'goods_receipt' when calling create_goods_receipt");
    }

    # parse inputs
    my $_resource_path = '/api/v1/goods-receipts';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'goods_receipt'}) {
        $_body_data = $args{'goods_receipt'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GoodsReceipt', $response);
    return $_response_object;
}

#
# delete_goods_receipt
#
# 
#
# @param string $goods_receipt_id  (required)
{
    my $params = {
    'goods_receipt_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_goods_receipt' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_goods_receipt {
    my ($self, %args) = @_;

    # verify the required parameter 'goods_receipt_id' is set
    unless (exists $args{'goods_receipt_id'}) {
      croak("Missing the required parameter 'goods_receipt_id' when calling delete_goods_receipt");
    }

    # parse inputs
    my $_resource_path = '/api/v1/goods-receipts/{goods_receipt_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'goods_receipt_id'}) {
        my $_base_variable = "{" . "goods_receipt_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'goods_receipt_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_goods_receipt
#
# 
#
# @param string $goods_receipt_id  (required)
{
    my $params = {
    'goods_receipt_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_goods_receipt' } = {
        summary => '',
        params => $params,
        returns => 'GoodsReceipt',
        };
}
# @return GoodsReceipt
#
sub get_goods_receipt {
    my ($self, %args) = @_;

    # verify the required parameter 'goods_receipt_id' is set
    unless (exists $args{'goods_receipt_id'}) {
      croak("Missing the required parameter 'goods_receipt_id' when calling get_goods_receipt");
    }

    # parse inputs
    my $_resource_path = '/api/v1/goods-receipts/{goods_receipt_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'goods_receipt_id'}) {
        my $_base_variable = "{" . "goods_receipt_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'goods_receipt_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GoodsReceipt', $response);
    return $_response_object;
}

#
# list_goods_receipts
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $purchase_order_id  (optional)
# @param string $supplier_name  (optional)
# @param string $warehouse_id  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'purchase_order_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_name' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'warehouse_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_goods_receipts' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[GoodsReceipt]',
        };
}
# @return ARRAY[GoodsReceipt]
#
sub list_goods_receipts {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/goods-receipts/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'purchase_order_id'}) {
        $query_params->{'purchase_order_id'} = $self->{api_client}->to_query_value($args{'purchase_order_id'});
    }

    # query params
    if ( exists $args{'supplier_name'}) {
        $query_params->{'supplier_name'} = $self->{api_client}->to_query_value($args{'supplier_name'});
    }

    # query params
    if ( exists $args{'warehouse_id'}) {
        $query_params->{'warehouse_id'} = $self->{api_client}->to_query_value($args{'warehouse_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[GoodsReceipt]', $response);
    return $_response_object;
}

1;
