=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::InventoryCountApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_inventory_count
#
# 
#
# @param InventoryCount $inventory_count  (required)
{
    my $params = {
    'inventory_count' => {
        data_type => 'InventoryCount',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_inventory_count' } = {
        summary => '',
        params => $params,
        returns => 'InventoryCount',
        };
}
# @return InventoryCount
#
sub create_inventory_count {
    my ($self, %args) = @_;

    # verify the required parameter 'inventory_count' is set
    unless (exists $args{'inventory_count'}) {
      croak("Missing the required parameter 'inventory_count' when calling create_inventory_count");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'inventory_count'}) {
        $_body_data = $args{'inventory_count'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InventoryCount', $response);
    return $_response_object;
}

#
# delete_inventory_count
#
# 
#
# @param string $inventory_count_id  (required)
{
    my $params = {
    'inventory_count_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_inventory_count' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_inventory_count {
    my ($self, %args) = @_;

    # verify the required parameter 'inventory_count_id' is set
    unless (exists $args{'inventory_count_id'}) {
      croak("Missing the required parameter 'inventory_count_id' when calling delete_inventory_count");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/{inventory_count_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'inventory_count_id'}) {
        my $_base_variable = "{" . "inventory_count_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inventory_count_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# generate_inventory_count
#
# 
#
# @param GenerateCountRequest $generate_count_request  (required)
{
    my $params = {
    'generate_count_request' => {
        data_type => 'GenerateCountRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'generate_inventory_count' } = {
        summary => '',
        params => $params,
        returns => 'InventoryCount',
        };
}
# @return InventoryCount
#
sub generate_inventory_count {
    my ($self, %args) = @_;

    # verify the required parameter 'generate_count_request' is set
    unless (exists $args{'generate_count_request'}) {
      croak("Missing the required parameter 'generate_count_request' when calling generate_inventory_count");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/generate';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'generate_count_request'}) {
        $_body_data = $args{'generate_count_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InventoryCount', $response);
    return $_response_object;
}

#
# get_inventory_count
#
# 
#
# @param string $inventory_count_id  (required)
{
    my $params = {
    'inventory_count_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_inventory_count' } = {
        summary => '',
        params => $params,
        returns => 'InventoryCount',
        };
}
# @return InventoryCount
#
sub get_inventory_count {
    my ($self, %args) = @_;

    # verify the required parameter 'inventory_count_id' is set
    unless (exists $args{'inventory_count_id'}) {
      croak("Missing the required parameter 'inventory_count_id' when calling get_inventory_count");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/{inventory_count_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'inventory_count_id'}) {
        my $_base_variable = "{" . "inventory_count_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inventory_count_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InventoryCount', $response);
    return $_response_object;
}

#
# list_inventory_counts
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $status  (optional)
# @param string $warehouse_id  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'status' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'warehouse_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_inventory_counts' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[InventoryCount]',
        };
}
# @return ARRAY[InventoryCount]
#
sub list_inventory_counts {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'status'}) {
        $query_params->{'status'} = $self->{api_client}->to_query_value($args{'status'});
    }

    # query params
    if ( exists $args{'warehouse_id'}) {
        $query_params->{'warehouse_id'} = $self->{api_client}->to_query_value($args{'warehouse_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[InventoryCount]', $response);
    return $_response_object;
}

#
# update_inventory_count
#
# 
#
# @param string $inventory_count_id  (required)
# @param object $body  (required)
{
    my $params = {
    'inventory_count_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_inventory_count' } = {
        summary => '',
        params => $params,
        returns => 'InventoryCount',
        };
}
# @return InventoryCount
#
sub update_inventory_count {
    my ($self, %args) = @_;

    # verify the required parameter 'inventory_count_id' is set
    unless (exists $args{'inventory_count_id'}) {
      croak("Missing the required parameter 'inventory_count_id' when calling update_inventory_count");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/{inventory_count_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'inventory_count_id'}) {
        my $_base_variable = "{" . "inventory_count_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inventory_count_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InventoryCount', $response);
    return $_response_object;
}

#
# update_inventory_count_status
#
# 
#
# @param string $inventory_count_id  (required)
# @param InventoryCountStatusUpdate $inventory_count_status_update  (required)
{
    my $params = {
    'inventory_count_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'inventory_count_status_update' => {
        data_type => 'InventoryCountStatusUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_inventory_count_status' } = {
        summary => '',
        params => $params,
        returns => 'InventoryCount',
        };
}
# @return InventoryCount
#
sub update_inventory_count_status {
    my ($self, %args) = @_;

    # verify the required parameter 'inventory_count_id' is set
    unless (exists $args{'inventory_count_id'}) {
      croak("Missing the required parameter 'inventory_count_id' when calling update_inventory_count_status");
    }

    # verify the required parameter 'inventory_count_status_update' is set
    unless (exists $args{'inventory_count_status_update'}) {
      croak("Missing the required parameter 'inventory_count_status_update' when calling update_inventory_count_status");
    }

    # parse inputs
    my $_resource_path = '/api/v1/inventory-counts/{inventory_count_id}/status';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'inventory_count_id'}) {
        my $_base_variable = "{" . "inventory_count_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inventory_count_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'inventory_count_status_update'}) {
        $_body_data = $args{'inventory_count_status_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InventoryCount', $response);
    return $_response_object;
}

1;
