=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::PackingApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# complete_packing
#
# Mark packing as complete and transition order to shipped
#
# @param string $order_number  (required)
# @param PackingCompleteRequest $packing_complete_request  (required)
{
    my $params = {
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'packing_complete_request' => {
        data_type => 'PackingCompleteRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'complete_packing' } = {
        summary => 'Mark packing as complete and transition order to shipped',
        params => $params,
        returns => 'PackingCompleteResponse',
        };
}
# @return PackingCompleteResponse
#
sub complete_packing {
    my ($self, %args) = @_;

    # verify the required parameter 'order_number' is set
    unless (exists $args{'order_number'}) {
      croak("Missing the required parameter 'order_number' when calling complete_packing");
    }

    # verify the required parameter 'packing_complete_request' is set
    unless (exists $args{'packing_complete_request'}) {
      croak("Missing the required parameter 'packing_complete_request' when calling complete_packing");
    }

    # parse inputs
    my $_resource_path = '/api/v1/packing/{order_number}/complete';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'order_number'}) {
        my $_base_variable = "{" . "order_number" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'order_number'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'packing_complete_request'}) {
        $_body_data = $args{'packing_complete_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PackingCompleteResponse', $response);
    return $_response_object;
}

#
# get_packing_queue
#
# Get the packing queue - orders ready for packing
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $search  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'search' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_packing_queue' } = {
        summary => 'Get the packing queue - orders ready for packing',
        params => $params,
        returns => 'PackingQueue',
        };
}
# @return PackingQueue
#
sub get_packing_queue {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/packing/queue';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'search'}) {
        $query_params->{'search'} = $self->{api_client}->to_query_value($args{'search'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PackingQueue', $response);
    return $_response_object;
}

#
# print_delivery_note
#
# Print delivery note (Lieferschein) for an order
#
# @param string $order_number  (required)
{
    my $params = {
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'print_delivery_note' } = {
        summary => 'Print delivery note (Lieferschein) for an order',
        params => $params,
        returns => 'PrintDeliveryNoteResponse',
        };
}
# @return PrintDeliveryNoteResponse
#
sub print_delivery_note {
    my ($self, %args) = @_;

    # verify the required parameter 'order_number' is set
    unless (exists $args{'order_number'}) {
      croak("Missing the required parameter 'order_number' when calling print_delivery_note");
    }

    # parse inputs
    my $_resource_path = '/api/v1/packing/{order_number}/print-delivery-note';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'order_number'}) {
        my $_base_variable = "{" . "order_number" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'order_number'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PrintDeliveryNoteResponse', $response);
    return $_response_object;
}

#
# print_label
#
# Print shipping label for an order
#
# @param string $order_number  (required)
{
    my $params = {
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'print_label' } = {
        summary => 'Print shipping label for an order',
        params => $params,
        returns => 'PrintLabelResponse',
        };
}
# @return PrintLabelResponse
#
sub print_label {
    my ($self, %args) = @_;

    # verify the required parameter 'order_number' is set
    unless (exists $args{'order_number'}) {
      croak("Missing the required parameter 'order_number' when calling print_label");
    }

    # parse inputs
    my $_resource_path = '/api/v1/packing/{order_number}/print-label';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'order_number'}) {
        my $_base_variable = "{" . "order_number" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'order_number'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PrintLabelResponse', $response);
    return $_response_object;
}

#
# record_packing_video
#
# Record video of packing process
#
# @param string $order_number  (required)
# @param object $body  (required)
{
    my $params = {
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'record_packing_video' } = {
        summary => 'Record video of packing process',
        params => $params,
        returns => 'PackingVideoResponse',
        };
}
# @return PackingVideoResponse
#
sub record_packing_video {
    my ($self, %args) = @_;

    # verify the required parameter 'order_number' is set
    unless (exists $args{'order_number'}) {
      croak("Missing the required parameter 'order_number' when calling record_packing_video");
    }

    # parse inputs
    my $_resource_path = '/api/v1/packing/{order_number}/record-video';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'order_number'}) {
        my $_base_variable = "{" . "order_number" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'order_number'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PackingVideoResponse', $response);
    return $_response_object;
}

1;
