=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::PriceTierApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_price_tier
#
# 
#
# @param PriceTierCreate $price_tier_create  (required)
{
    my $params = {
    'price_tier_create' => {
        data_type => 'PriceTierCreate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_price_tier' } = {
        summary => '',
        params => $params,
        returns => 'PriceTier',
        };
}
# @return PriceTier
#
sub create_price_tier {
    my ($self, %args) = @_;

    # verify the required parameter 'price_tier_create' is set
    unless (exists $args{'price_tier_create'}) {
      croak("Missing the required parameter 'price_tier_create' when calling create_price_tier");
    }

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'price_tier_create'}) {
        $_body_data = $args{'price_tier_create'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PriceTier', $response);
    return $_response_object;
}

#
# delete_price_tier
#
# 
#
# @param string $price_tier_id  (required)
{
    my $params = {
    'price_tier_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_price_tier' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_price_tier {
    my ($self, %args) = @_;

    # verify the required parameter 'price_tier_id' is set
    unless (exists $args{'price_tier_id'}) {
      croak("Missing the required parameter 'price_tier_id' when calling delete_price_tier");
    }

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers/{price_tier_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'price_tier_id'}) {
        my $_base_variable = "{" . "price_tier_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'price_tier_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_price_tier
#
# 
#
# @param string $price_tier_id  (required)
{
    my $params = {
    'price_tier_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_price_tier' } = {
        summary => '',
        params => $params,
        returns => 'PriceTier',
        };
}
# @return PriceTier
#
sub get_price_tier {
    my ($self, %args) = @_;

    # verify the required parameter 'price_tier_id' is set
    unless (exists $args{'price_tier_id'}) {
      croak("Missing the required parameter 'price_tier_id' when calling get_price_tier");
    }

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers/{price_tier_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'price_tier_id'}) {
        my $_base_variable = "{" . "price_tier_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'price_tier_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PriceTier', $response);
    return $_response_object;
}

#
# get_resolved_price
#
# 
#
# @param string $product_id  (required)
# @param int $quantity  (optional)
# @param string $contact_id Contact used to match customer-group-scoped tiers. (optional)
{
    my $params = {
    'product_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'quantity' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'contact_id' => {
        data_type => 'string',
        description => 'Contact used to match customer-group-scoped tiers.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_resolved_price' } = {
        summary => '',
        params => $params,
        returns => 'ResolvedPriceResponse',
        };
}
# @return ResolvedPriceResponse
#
sub get_resolved_price {
    my ($self, %args) = @_;

    # verify the required parameter 'product_id' is set
    unless (exists $args{'product_id'}) {
      croak("Missing the required parameter 'product_id' when calling get_resolved_price");
    }

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers/resolved';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'product_id'}) {
        $query_params->{'productId'} = $self->{api_client}->to_query_value($args{'product_id'});
    }

    # query params
    if ( exists $args{'quantity'}) {
        $query_params->{'quantity'} = $self->{api_client}->to_query_value($args{'quantity'});
    }

    # query params
    if ( exists $args{'contact_id'}) {
        $query_params->{'contactId'} = $self->{api_client}->to_query_value($args{'contact_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ResolvedPriceResponse', $response);
    return $_response_object;
}

#
# list_price_tiers
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $product_id  (optional)
# @param string $customer_group_id  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'product_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'customer_group_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_price_tiers' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[PriceTier]',
        };
}
# @return ARRAY[PriceTier]
#
sub list_price_tiers {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'product_id'}) {
        $query_params->{'product_id'} = $self->{api_client}->to_query_value($args{'product_id'});
    }

    # query params
    if ( exists $args{'customer_group_id'}) {
        $query_params->{'customer_group_id'} = $self->{api_client}->to_query_value($args{'customer_group_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[PriceTier]', $response);
    return $_response_object;
}

#
# update_price_tier
#
# 
#
# @param string $price_tier_id  (required)
# @param PriceTierUpdate $price_tier_update  (required)
{
    my $params = {
    'price_tier_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'price_tier_update' => {
        data_type => 'PriceTierUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_price_tier' } = {
        summary => '',
        params => $params,
        returns => 'PriceTier',
        };
}
# @return PriceTier
#
sub update_price_tier {
    my ($self, %args) = @_;

    # verify the required parameter 'price_tier_id' is set
    unless (exists $args{'price_tier_id'}) {
      croak("Missing the required parameter 'price_tier_id' when calling update_price_tier");
    }

    # verify the required parameter 'price_tier_update' is set
    unless (exists $args{'price_tier_update'}) {
      croak("Missing the required parameter 'price_tier_update' when calling update_price_tier");
    }

    # parse inputs
    my $_resource_path = '/api/v1/price-tiers/{price_tier_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'price_tier_id'}) {
        my $_base_variable = "{" . "price_tier_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'price_tier_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'price_tier_update'}) {
        $_body_data = $args{'price_tier_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PriceTier', $response);
    return $_response_object;
}

1;
