=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::ProductVariantApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_product_variant
#
# 
#
# @param ProductVariant $product_variant  (required)
{
    my $params = {
    'product_variant' => {
        data_type => 'ProductVariant',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_product_variant' } = {
        summary => '',
        params => $params,
        returns => 'ProductVariant',
        };
}
# @return ProductVariant
#
sub create_product_variant {
    my ($self, %args) = @_;

    # verify the required parameter 'product_variant' is set
    unless (exists $args{'product_variant'}) {
      croak("Missing the required parameter 'product_variant' when calling create_product_variant");
    }

    # parse inputs
    my $_resource_path = '/api/v1/product-variants';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'product_variant'}) {
        $_body_data = $args{'product_variant'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProductVariant', $response);
    return $_response_object;
}

#
# delete_product_variant
#
# 
#
# @param string $variant_id  (required)
{
    my $params = {
    'variant_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_product_variant' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_product_variant {
    my ($self, %args) = @_;

    # verify the required parameter 'variant_id' is set
    unless (exists $args{'variant_id'}) {
      croak("Missing the required parameter 'variant_id' when calling delete_product_variant");
    }

    # parse inputs
    my $_resource_path = '/api/v1/product-variants/{variant_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'variant_id'}) {
        my $_base_variable = "{" . "variant_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'variant_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# generate_product_variants
#
# 
#
# @param GenerateVariantsRequest $generate_variants_request  (required)
{
    my $params = {
    'generate_variants_request' => {
        data_type => 'GenerateVariantsRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'generate_product_variants' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[ProductVariant]',
        };
}
# @return ARRAY[ProductVariant]
#
sub generate_product_variants {
    my ($self, %args) = @_;

    # verify the required parameter 'generate_variants_request' is set
    unless (exists $args{'generate_variants_request'}) {
      croak("Missing the required parameter 'generate_variants_request' when calling generate_product_variants");
    }

    # parse inputs
    my $_resource_path = '/api/v1/product-variants/generate';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'generate_variants_request'}) {
        $_body_data = $args{'generate_variants_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[ProductVariant]', $response);
    return $_response_object;
}

#
# get_product_variant
#
# 
#
# @param string $variant_id  (required)
{
    my $params = {
    'variant_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_product_variant' } = {
        summary => '',
        params => $params,
        returns => 'ProductVariant',
        };
}
# @return ProductVariant
#
sub get_product_variant {
    my ($self, %args) = @_;

    # verify the required parameter 'variant_id' is set
    unless (exists $args{'variant_id'}) {
      croak("Missing the required parameter 'variant_id' when calling get_product_variant");
    }

    # parse inputs
    my $_resource_path = '/api/v1/product-variants/{variant_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'variant_id'}) {
        my $_base_variable = "{" . "variant_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'variant_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProductVariant', $response);
    return $_response_object;
}

#
# list_product_variants
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $product_id  (optional)
# @param boolean $is_active  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'product_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'is_active' => {
        data_type => 'boolean',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_product_variants' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[ProductVariant]',
        };
}
# @return ARRAY[ProductVariant]
#
sub list_product_variants {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/product-variants/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'product_id'}) {
        $query_params->{'product_id'} = $self->{api_client}->to_query_value($args{'product_id'});
    }

    # query params
    if ( exists $args{'is_active'}) {
        $query_params->{'is_active'} = $self->{api_client}->to_query_value($args{'is_active'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[ProductVariant]', $response);
    return $_response_object;
}

#
# update_product_variant
#
# 
#
# @param string $variant_id  (required)
# @param object $body  (required)
{
    my $params = {
    'variant_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_product_variant' } = {
        summary => '',
        params => $params,
        returns => 'ProductVariant',
        };
}
# @return ProductVariant
#
sub update_product_variant {
    my ($self, %args) = @_;

    # verify the required parameter 'variant_id' is set
    unless (exists $args{'variant_id'}) {
      croak("Missing the required parameter 'variant_id' when calling update_product_variant");
    }

    # parse inputs
    my $_resource_path = '/api/v1/product-variants/{variant_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'variant_id'}) {
        my $_base_variable = "{" . "variant_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'variant_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProductVariant', $response);
    return $_response_object;
}

1;
