=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::ProformaInvoiceApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# convert_proforma_to_invoice
#
# 
#
# @param string $proforma_id  (required)
{
    my $params = {
    'proforma_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'convert_proforma_to_invoice' } = {
        summary => '',
        params => $params,
        returns => 'ConvertResponse',
        };
}
# @return ConvertResponse
#
sub convert_proforma_to_invoice {
    my ($self, %args) = @_;

    # verify the required parameter 'proforma_id' is set
    unless (exists $args{'proforma_id'}) {
      croak("Missing the required parameter 'proforma_id' when calling convert_proforma_to_invoice");
    }

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices/{proforma_id}/convert';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'proforma_id'}) {
        my $_base_variable = "{" . "proforma_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'proforma_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ConvertResponse', $response);
    return $_response_object;
}

#
# create_proforma_invoice
#
# 
#
# @param ProformaInvoice $proforma_invoice  (required)
{
    my $params = {
    'proforma_invoice' => {
        data_type => 'ProformaInvoice',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_proforma_invoice' } = {
        summary => '',
        params => $params,
        returns => 'ProformaInvoice',
        };
}
# @return ProformaInvoice
#
sub create_proforma_invoice {
    my ($self, %args) = @_;

    # verify the required parameter 'proforma_invoice' is set
    unless (exists $args{'proforma_invoice'}) {
      croak("Missing the required parameter 'proforma_invoice' when calling create_proforma_invoice");
    }

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'proforma_invoice'}) {
        $_body_data = $args{'proforma_invoice'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProformaInvoice', $response);
    return $_response_object;
}

#
# delete_proforma_invoice
#
# 
#
# @param string $proforma_id  (required)
{
    my $params = {
    'proforma_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_proforma_invoice' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_proforma_invoice {
    my ($self, %args) = @_;

    # verify the required parameter 'proforma_id' is set
    unless (exists $args{'proforma_id'}) {
      croak("Missing the required parameter 'proforma_id' when calling delete_proforma_invoice");
    }

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices/{proforma_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'proforma_id'}) {
        my $_base_variable = "{" . "proforma_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'proforma_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_proforma_invoice
#
# 
#
# @param string $proforma_id  (required)
{
    my $params = {
    'proforma_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_proforma_invoice' } = {
        summary => '',
        params => $params,
        returns => 'ProformaInvoice',
        };
}
# @return ProformaInvoice
#
sub get_proforma_invoice {
    my ($self, %args) = @_;

    # verify the required parameter 'proforma_id' is set
    unless (exists $args{'proforma_id'}) {
      croak("Missing the required parameter 'proforma_id' when calling get_proforma_invoice");
    }

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices/{proforma_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'proforma_id'}) {
        my $_base_variable = "{" . "proforma_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'proforma_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProformaInvoice', $response);
    return $_response_object;
}

#
# list_proforma_invoices
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $status  (optional)
# @param string $customer_id  (optional)
# @param string $order_number  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'status' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'customer_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_proforma_invoices' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[ProformaInvoice]',
        };
}
# @return ARRAY[ProformaInvoice]
#
sub list_proforma_invoices {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'status'}) {
        $query_params->{'status'} = $self->{api_client}->to_query_value($args{'status'});
    }

    # query params
    if ( exists $args{'customer_id'}) {
        $query_params->{'customer_id'} = $self->{api_client}->to_query_value($args{'customer_id'});
    }

    # query params
    if ( exists $args{'order_number'}) {
        $query_params->{'order_number'} = $self->{api_client}->to_query_value($args{'order_number'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[ProformaInvoice]', $response);
    return $_response_object;
}

#
# update_proforma_invoice
#
# 
#
# @param string $proforma_id  (required)
# @param object $body  (required)
{
    my $params = {
    'proforma_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_proforma_invoice' } = {
        summary => '',
        params => $params,
        returns => 'ProformaInvoice',
        };
}
# @return ProformaInvoice
#
sub update_proforma_invoice {
    my ($self, %args) = @_;

    # verify the required parameter 'proforma_id' is set
    unless (exists $args{'proforma_id'}) {
      croak("Missing the required parameter 'proforma_id' when calling update_proforma_invoice");
    }

    # parse inputs
    my $_resource_path = '/api/v1/proforma-invoices/{proforma_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'proforma_id'}) {
        my $_base_variable = "{" . "proforma_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'proforma_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ProformaInvoice', $response);
    return $_response_object;
}

1;
