=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::ShippingRuleApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_shipping_rule
#
# 
#
# @param ShippingRuleCreate $shipping_rule_create  (required)
{
    my $params = {
    'shipping_rule_create' => {
        data_type => 'ShippingRuleCreate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_shipping_rule' } = {
        summary => '',
        params => $params,
        returns => 'ShippingRule',
        };
}
# @return ShippingRule
#
sub create_shipping_rule {
    my ($self, %args) = @_;

    # verify the required parameter 'shipping_rule_create' is set
    unless (exists $args{'shipping_rule_create'}) {
      croak("Missing the required parameter 'shipping_rule_create' when calling create_shipping_rule");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipping-rules';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'shipping_rule_create'}) {
        $_body_data = $args{'shipping_rule_create'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ShippingRule', $response);
    return $_response_object;
}

#
# delete_shipping_rule
#
# 
#
# @param string $rule_id  (required)
{
    my $params = {
    'rule_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_shipping_rule' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_shipping_rule {
    my ($self, %args) = @_;

    # verify the required parameter 'rule_id' is set
    unless (exists $args{'rule_id'}) {
      croak("Missing the required parameter 'rule_id' when calling delete_shipping_rule");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipping-rules/{rule_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'rule_id'}) {
        my $_base_variable = "{" . "rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_shipping_rule
#
# 
#
# @param string $rule_id  (required)
{
    my $params = {
    'rule_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_shipping_rule' } = {
        summary => '',
        params => $params,
        returns => 'ShippingRule',
        };
}
# @return ShippingRule
#
sub get_shipping_rule {
    my ($self, %args) = @_;

    # verify the required parameter 'rule_id' is set
    unless (exists $args{'rule_id'}) {
      croak("Missing the required parameter 'rule_id' when calling get_shipping_rule");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipping-rules/{rule_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'rule_id'}) {
        my $_base_variable = "{" . "rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ShippingRule', $response);
    return $_response_object;
}

#
# list_shipping_rules
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $country  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'country' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_shipping_rules' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[ShippingRule]',
        };
}
# @return ARRAY[ShippingRule]
#
sub list_shipping_rules {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/shipping-rules/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'country'}) {
        $query_params->{'country'} = $self->{api_client}->to_query_value($args{'country'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[ShippingRule]', $response);
    return $_response_object;
}

#
# update_shipping_rule
#
# 
#
# @param string $rule_id  (required)
# @param ShippingRuleUpdate $shipping_rule_update  (required)
{
    my $params = {
    'rule_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'shipping_rule_update' => {
        data_type => 'ShippingRuleUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_shipping_rule' } = {
        summary => '',
        params => $params,
        returns => 'ShippingRule',
        };
}
# @return ShippingRule
#
sub update_shipping_rule {
    my ($self, %args) = @_;

    # verify the required parameter 'rule_id' is set
    unless (exists $args{'rule_id'}) {
      croak("Missing the required parameter 'rule_id' when calling update_shipping_rule");
    }

    # verify the required parameter 'shipping_rule_update' is set
    unless (exists $args{'shipping_rule_update'}) {
      croak("Missing the required parameter 'shipping_rule_update' when calling update_shipping_rule");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipping-rules/{rule_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'rule_id'}) {
        my $_base_variable = "{" . "rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'shipping_rule_update'}) {
        $_body_data = $args{'shipping_rule_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ShippingRule', $response);
    return $_response_object;
}

1;
