=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::ShipmentApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_shipment
#
# 
#
# @param Shipment $shipment  (required)
{
    my $params = {
    'shipment' => {
        data_type => 'Shipment',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_shipment' } = {
        summary => '',
        params => $params,
        returns => 'Shipment',
        };
}
# @return Shipment
#
sub create_shipment {
    my ($self, %args) = @_;

    # verify the required parameter 'shipment' is set
    unless (exists $args{'shipment'}) {
      croak("Missing the required parameter 'shipment' when calling create_shipment");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipments';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'shipment'}) {
        $_body_data = $args{'shipment'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Shipment', $response);
    return $_response_object;
}

#
# create_shipment_from_order
#
# Create a real shipment for an order: calls the configured carrier's label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.
#
# @param string $order_number  (required)
# @param CreateShipmentRequest $create_shipment_request  (required)
{
    my $params = {
    'order_number' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'create_shipment_request' => {
        data_type => 'CreateShipmentRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_shipment_from_order' } = {
        summary => 'Create a real shipment for an order: calls the configured carrier&#39;s label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.',
        params => $params,
        returns => 'Shipment',
        };
}
# @return Shipment
#
sub create_shipment_from_order {
    my ($self, %args) = @_;

    # verify the required parameter 'order_number' is set
    unless (exists $args{'order_number'}) {
      croak("Missing the required parameter 'order_number' when calling create_shipment_from_order");
    }

    # verify the required parameter 'create_shipment_request' is set
    unless (exists $args{'create_shipment_request'}) {
      croak("Missing the required parameter 'create_shipment_request' when calling create_shipment_from_order");
    }

    # parse inputs
    my $_resource_path = '/api/v1/orders/{order_number}/shipments';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'order_number'}) {
        my $_base_variable = "{" . "order_number" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'order_number'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'create_shipment_request'}) {
        $_body_data = $args{'create_shipment_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Shipment', $response);
    return $_response_object;
}

#
# delete_shipment
#
# 
#
# @param string $shipment_id  (required)
{
    my $params = {
    'shipment_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_shipment' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_shipment {
    my ($self, %args) = @_;

    # verify the required parameter 'shipment_id' is set
    unless (exists $args{'shipment_id'}) {
      croak("Missing the required parameter 'shipment_id' when calling delete_shipment");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipments/{shipment_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'shipment_id'}) {
        my $_base_variable = "{" . "shipment_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'shipment_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_shipment
#
# 
#
# @param string $shipment_id  (required)
{
    my $params = {
    'shipment_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_shipment' } = {
        summary => '',
        params => $params,
        returns => 'Shipment',
        };
}
# @return Shipment
#
sub get_shipment {
    my ($self, %args) = @_;

    # verify the required parameter 'shipment_id' is set
    unless (exists $args{'shipment_id'}) {
      croak("Missing the required parameter 'shipment_id' when calling get_shipment");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipments/{shipment_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'shipment_id'}) {
        my $_base_variable = "{" . "shipment_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'shipment_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Shipment', $response);
    return $_response_object;
}

#
# list_shipments
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $search  (optional)
# @param boolean $include_deleted Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'search' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'include_deleted' => {
        data_type => 'boolean',
        description => 'Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_shipments' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[Shipment]',
        };
}
# @return ARRAY[Shipment]
#
sub list_shipments {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/shipments';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'search'}) {
        $query_params->{'search'} = $self->{api_client}->to_query_value($args{'search'});
    }

    # query params
    if ( exists $args{'include_deleted'}) {
        $query_params->{'include_deleted'} = $self->{api_client}->to_query_value($args{'include_deleted'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Shipment]', $response);
    return $_response_object;
}

#
# track_order_public
#
# Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).
#
# @param TrackOrderRequest $track_order_request  (required)
{
    my $params = {
    'track_order_request' => {
        data_type => 'TrackOrderRequest',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'track_order_public' } = {
        summary => 'Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).',
        params => $params,
        returns => 'TrackOrderResponse',
        };
}
# @return TrackOrderResponse
#
sub track_order_public {
    my ($self, %args) = @_;

    # verify the required parameter 'track_order_request' is set
    unless (exists $args{'track_order_request'}) {
      croak("Missing the required parameter 'track_order_request' when calling track_order_public");
    }

    # parse inputs
    my $_resource_path = '/api/v1/public/track';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'track_order_request'}) {
        $_body_data = $args{'track_order_request'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TrackOrderResponse', $response);
    return $_response_object;
}

#
# track_shipment_api
#
# 
#
# @param string $shipment_id  (required)
{
    my $params = {
    'shipment_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'track_shipment_api' } = {
        summary => '',
        params => $params,
        returns => 'TrackingInfo',
        };
}
# @return TrackingInfo
#
sub track_shipment_api {
    my ($self, %args) = @_;

    # verify the required parameter 'shipment_id' is set
    unless (exists $args{'shipment_id'}) {
      croak("Missing the required parameter 'shipment_id' when calling track_shipment_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipments/{shipment_id}/tracking';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'shipment_id'}) {
        my $_base_variable = "{" . "shipment_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'shipment_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TrackingInfo', $response);
    return $_response_object;
}

#
# update_shipment_status
#
# 
#
# @param string $shipment_id  (required)
# @param ShipmentStatusUpdate $shipment_status_update  (required)
{
    my $params = {
    'shipment_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'shipment_status_update' => {
        data_type => 'ShipmentStatusUpdate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_shipment_status' } = {
        summary => '',
        params => $params,
        returns => 'Shipment',
        };
}
# @return Shipment
#
sub update_shipment_status {
    my ($self, %args) = @_;

    # verify the required parameter 'shipment_id' is set
    unless (exists $args{'shipment_id'}) {
      croak("Missing the required parameter 'shipment_id' when calling update_shipment_status");
    }

    # verify the required parameter 'shipment_status_update' is set
    unless (exists $args{'shipment_status_update'}) {
      croak("Missing the required parameter 'shipment_status_update' when calling update_shipment_status");
    }

    # parse inputs
    my $_resource_path = '/api/v1/shipments/{shipment_id}/status';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'shipment_id'}) {
        my $_base_variable = "{" . "shipment_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'shipment_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'shipment_status_update'}) {
        $_body_data = $args{'shipment_status_update'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Shipment', $response);
    return $_response_object;
}

1;
