=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::TimeEntriesApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# clock_in_time_entry
#
# Clock in for the authenticated user (resolved via their employee profile).
#
# @param TimeEntryClockIn $time_entry_clock_in  (required)
{
    my $params = {
    'time_entry_clock_in' => {
        data_type => 'TimeEntryClockIn',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'clock_in_time_entry' } = {
        summary => 'Clock in for the authenticated user (resolved via their employee profile).',
        params => $params,
        returns => 'TimeEntryDto',
        };
}
# @return TimeEntryDto
#
sub clock_in_time_entry {
    my ($self, %args) = @_;

    # verify the required parameter 'time_entry_clock_in' is set
    unless (exists $args{'time_entry_clock_in'}) {
      croak("Missing the required parameter 'time_entry_clock_in' when calling clock_in_time_entry");
    }

    # parse inputs
    my $_resource_path = '/api/v1/time-entries';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'time_entry_clock_in'}) {
        $_body_data = $args{'time_entry_clock_in'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TimeEntryDto', $response);
    return $_response_object;
}

#
# clock_out_time_entry
#
# Clock out an entry: the entry's owner, or anyone with `time_entries:write`.
#
# @param string $id  (required)
# @param TimeEntryClockOut $time_entry_clock_out  (required)
{
    my $params = {
    'id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'time_entry_clock_out' => {
        data_type => 'TimeEntryClockOut',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'clock_out_time_entry' } = {
        summary => 'Clock out an entry: the entry&#39;s owner, or anyone with &#x60;time_entries:write&#x60;.',
        params => $params,
        returns => 'TimeEntryDto',
        };
}
# @return TimeEntryDto
#
sub clock_out_time_entry {
    my ($self, %args) = @_;

    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling clock_out_time_entry");
    }

    # verify the required parameter 'time_entry_clock_out' is set
    unless (exists $args{'time_entry_clock_out'}) {
      croak("Missing the required parameter 'time_entry_clock_out' when calling clock_out_time_entry");
    }

    # parse inputs
    my $_resource_path = '/api/v1/time-entries/{id}';

    my $_method = 'PATCH';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'time_entry_clock_out'}) {
        $_body_data = $args{'time_entry_clock_out'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('TimeEntryDto', $response);
    return $_response_object;
}

#
# get_labor_costs
#
# Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee's hourly cost rate.
#
# @param DATE $from  (required)
# @param DATE $to  (required)
# @param string $group_by One of \&quot;employee\&quot;, \&quot;order\&quot; or \&quot;day\&quot;. (required)
{
    my $params = {
    'from' => {
        data_type => 'DATE',
        description => '',
        required => '1',
    },
    'to' => {
        data_type => 'DATE',
        description => '',
        required => '1',
    },
    'group_by' => {
        data_type => 'string',
        description => 'One of \&quot;employee\&quot;, \&quot;order\&quot; or \&quot;day\&quot;.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_labor_costs' } = {
        summary => 'Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee&#39;s hourly cost rate.',
        params => $params,
        returns => 'ARRAY[LaborCostRow]',
        };
}
# @return ARRAY[LaborCostRow]
#
sub get_labor_costs {
    my ($self, %args) = @_;

    # verify the required parameter 'from' is set
    unless (exists $args{'from'}) {
      croak("Missing the required parameter 'from' when calling get_labor_costs");
    }

    # verify the required parameter 'to' is set
    unless (exists $args{'to'}) {
      croak("Missing the required parameter 'to' when calling get_labor_costs");
    }

    # verify the required parameter 'group_by' is set
    unless (exists $args{'group_by'}) {
      croak("Missing the required parameter 'group_by' when calling get_labor_costs");
    }

    # parse inputs
    my $_resource_path = '/api/v1/labor-costs';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'from'}) {
        $query_params->{'from'} = $self->{api_client}->to_query_value($args{'from'});
    }

    # query params
    if ( exists $args{'to'}) {
        $query_params->{'to'} = $self->{api_client}->to_query_value($args{'to'});
    }

    # query params
    if ( exists $args{'group_by'}) {
        $query_params->{'group_by'} = $self->{api_client}->to_query_value($args{'group_by'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[LaborCostRow]', $response);
    return $_response_object;
}

#
# list_time_entries
#
# List time entries with optional date-range / active / employee filters.
#
# @param DATE $from  (optional)
# @param DATE $to  (optional)
# @param boolean $active Only currently running shifts (clock_in set, clock_out null). (optional)
# @param string $employee_id  (optional)
{
    my $params = {
    'from' => {
        data_type => 'DATE',
        description => '',
        required => '0',
    },
    'to' => {
        data_type => 'DATE',
        description => '',
        required => '0',
    },
    'active' => {
        data_type => 'boolean',
        description => 'Only currently running shifts (clock_in set, clock_out null).',
        required => '0',
    },
    'employee_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_time_entries' } = {
        summary => 'List time entries with optional date-range / active / employee filters.',
        params => $params,
        returns => 'ARRAY[TimeEntryDto]',
        };
}
# @return ARRAY[TimeEntryDto]
#
sub list_time_entries {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/time-entries';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'from'}) {
        $query_params->{'from'} = $self->{api_client}->to_query_value($args{'from'});
    }

    # query params
    if ( exists $args{'to'}) {
        $query_params->{'to'} = $self->{api_client}->to_query_value($args{'to'});
    }

    # query params
    if ( exists $args{'active'}) {
        $query_params->{'active'} = $self->{api_client}->to_query_value($args{'active'});
    }

    # query params
    if ( exists $args{'employee_id'}) {
        $query_params->{'employee_id'} = $self->{api_client}->to_query_value($args{'employee_id'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[TimeEntryDto]', $response);
    return $_response_object;
}

1;
