=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::VoucherApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# create_voucher
#
# 
#
# @param VoucherCreate $voucher_create  (required)
{
    my $params = {
    'voucher_create' => {
        data_type => 'VoucherCreate',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'create_voucher' } = {
        summary => '',
        params => $params,
        returns => 'Voucher',
        };
}
# @return Voucher
#
sub create_voucher {
    my ($self, %args) = @_;

    # verify the required parameter 'voucher_create' is set
    unless (exists $args{'voucher_create'}) {
      croak("Missing the required parameter 'voucher_create' when calling create_voucher");
    }

    # parse inputs
    my $_resource_path = '/api/v1/vouchers';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'voucher_create'}) {
        $_body_data = $args{'voucher_create'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Voucher', $response);
    return $_response_object;
}

#
# delete_voucher
#
# 
#
# @param string $voucher_id  (required)
{
    my $params = {
    'voucher_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'delete_voucher' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub delete_voucher {
    my ($self, %args) = @_;

    # verify the required parameter 'voucher_id' is set
    unless (exists $args{'voucher_id'}) {
      croak("Missing the required parameter 'voucher_id' when calling delete_voucher");
    }

    # parse inputs
    my $_resource_path = '/api/v1/vouchers/{voucher_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'voucher_id'}) {
        my $_base_variable = "{" . "voucher_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'voucher_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# get_voucher
#
# 
#
# @param string $voucher_id  (required)
{
    my $params = {
    'voucher_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_voucher' } = {
        summary => '',
        params => $params,
        returns => 'Voucher',
        };
}
# @return Voucher
#
sub get_voucher {
    my ($self, %args) = @_;

    # verify the required parameter 'voucher_id' is set
    unless (exists $args{'voucher_id'}) {
      croak("Missing the required parameter 'voucher_id' when calling get_voucher");
    }

    # parse inputs
    my $_resource_path = '/api/v1/vouchers/{voucher_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'voucher_id'}) {
        my $_base_variable = "{" . "voucher_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'voucher_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Voucher', $response);
    return $_response_object;
}

#
# list_vouchers
#
# 
#
# @param int $page  (optional)
# @param int $page_size  (optional)
# @param string $voucher_type  (optional)
# @param string $voucher_status  (optional)
# @param string $contact_name  (optional)
# @param DATE $date_from  (optional)
# @param DATE $date_to  (optional)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'page_size' => {
        data_type => 'int',
        description => '',
        required => '0',
    },
    'voucher_type' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'voucher_status' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'contact_name' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'date_from' => {
        data_type => 'DATE',
        description => '',
        required => '0',
    },
    'date_to' => {
        data_type => 'DATE',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'list_vouchers' } = {
        summary => '',
        params => $params,
        returns => 'ARRAY[Voucher]',
        };
}
# @return ARRAY[Voucher]
#
sub list_vouchers {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/api/v1/vouchers/';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'page_size'}) {
        $query_params->{'page_size'} = $self->{api_client}->to_query_value($args{'page_size'});
    }

    # query params
    if ( exists $args{'voucher_type'}) {
        $query_params->{'voucher_type'} = $self->{api_client}->to_query_value($args{'voucher_type'});
    }

    # query params
    if ( exists $args{'voucher_status'}) {
        $query_params->{'voucher_status'} = $self->{api_client}->to_query_value($args{'voucher_status'});
    }

    # query params
    if ( exists $args{'contact_name'}) {
        $query_params->{'contact_name'} = $self->{api_client}->to_query_value($args{'contact_name'});
    }

    # query params
    if ( exists $args{'date_from'}) {
        $query_params->{'date_from'} = $self->{api_client}->to_query_value($args{'date_from'});
    }

    # query params
    if ( exists $args{'date_to'}) {
        $query_params->{'date_to'} = $self->{api_client}->to_query_value($args{'date_to'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('ARRAY[Voucher]', $response);
    return $_response_object;
}

#
# update_voucher
#
# 
#
# @param string $voucher_id  (required)
# @param object $body  (required)
{
    my $params = {
    'voucher_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'body' => {
        data_type => 'object',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'update_voucher' } = {
        summary => '',
        params => $params,
        returns => 'Voucher',
        };
}
# @return Voucher
#
sub update_voucher {
    my ($self, %args) = @_;

    # verify the required parameter 'voucher_id' is set
    unless (exists $args{'voucher_id'}) {
      croak("Missing the required parameter 'voucher_id' when calling update_voucher");
    }

    # parse inputs
    my $_resource_path = '/api/v1/vouchers/{voucher_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'voucher_id'}) {
        my $_base_variable = "{" . "voucher_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'voucher_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Voucher', $response);
    return $_response_object;
}

#
# voucher_restore
#
# 
#
# @param string $voucher_id  (required)
{
    my $params = {
    'voucher_id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'voucher_restore' } = {
        summary => '',
        params => $params,
        returns => 'Voucher',
        };
}
# @return Voucher
#
sub voucher_restore {
    my ($self, %args) = @_;

    # verify the required parameter 'voucher_id' is set
    unless (exists $args{'voucher_id'}) {
      croak("Missing the required parameter 'voucher_id' when calling voucher_restore");
    }

    # parse inputs
    my $_resource_path = '/api/v1/vouchers/{voucher_id}/restore';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # path params
    if ( exists $args{'voucher_id'}) {
        my $_base_variable = "{" . "voucher_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'voucher_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Voucher', $response);
    return $_response_object;
}

1;
