=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::ZugferdApi;

require 5.6.0;
use strict;
use warnings;
use utf8;
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# generate_zugferd_api
#
# 
#
# @param string $id  (required)
# @param string $supplier_name  (optional)
# @param string $supplier_street  (optional)
# @param string $supplier_city  (optional)
# @param string $supplier_zip  (optional)
# @param string $supplier_country  (optional)
# @param string $supplier_vat_id  (optional)
{
    my $params = {
    'id' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'supplier_name' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_street' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_city' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_zip' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_country' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    'supplier_vat_id' => {
        data_type => 'string',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'generate_zugferd_api' } = {
        summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub generate_zugferd_api {
    my ($self, %args) = @_;

    # verify the required parameter 'id' is set
    unless (exists $args{'id'}) {
      croak("Missing the required parameter 'id' when calling generate_zugferd_api");
    }

    # parse inputs
    my $_resource_path = '/api/v1/invoices/{id}/zugferd';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/pdf');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'supplier_name'}) {
        $query_params->{'supplier_name'} = $self->{api_client}->to_query_value($args{'supplier_name'});
    }

    # query params
    if ( exists $args{'supplier_street'}) {
        $query_params->{'supplier_street'} = $self->{api_client}->to_query_value($args{'supplier_street'});
    }

    # query params
    if ( exists $args{'supplier_city'}) {
        $query_params->{'supplier_city'} = $self->{api_client}->to_query_value($args{'supplier_city'});
    }

    # query params
    if ( exists $args{'supplier_zip'}) {
        $query_params->{'supplier_zip'} = $self->{api_client}->to_query_value($args{'supplier_zip'});
    }

    # query params
    if ( exists $args{'supplier_country'}) {
        $query_params->{'supplier_country'} = $self->{api_client}->to_query_value($args{'supplier_country'});
    }

    # query params
    if ( exists $args{'supplier_vat_id'}) {
        $query_params->{'supplier_vat_id'} = $self->{api_client}->to_query_value($args{'supplier_vat_id'});
    }

    # path params
    if ( exists $args{'id'}) {
        my $_base_variable = "{" . "id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(bearer_token )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
