=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::AbsenceApi');

my $api = WWW::OpenAPIClient::AbsenceApi->new();
isa_ok($api, 'WWW::OpenAPIClient::AbsenceApi');

#
# create_absence test
#
# uncomment below and update the test
#my $create_absence_absence_create = undef; # replace NULL with a proper value
#my $create_absence_result = $api->create_absence(absence_create => $create_absence_absence_create);

#
# delete_absence test
#
# uncomment below and update the test
#my $delete_absence_id = undef; # replace NULL with a proper value
#my $delete_absence_result = $api->delete_absence(id => $delete_absence_id);

#
# get_absence test
#
# uncomment below and update the test
#my $get_absence_id = undef; # replace NULL with a proper value
#my $get_absence_result = $api->get_absence(id => $get_absence_id);

#
# get_absences test
#
# uncomment below and update the test
#my $get_absences_page = undef; # replace NULL with a proper value
#my $get_absences_page_size = undef; # replace NULL with a proper value
#my $get_absences_search = undef; # replace NULL with a proper value
#my $get_absences_include_deleted = undef; # replace NULL with a proper value
#my $get_absences_result = $api->get_absences(page => $get_absences_page, page_size => $get_absences_page_size, search => $get_absences_search, include_deleted => $get_absences_include_deleted);

#
# update_absence test
#
# uncomment below and update the test
#my $update_absence_id = undef; # replace NULL with a proper value
#my $update_absence_absence_update = undef; # replace NULL with a proper value
#my $update_absence_result = $api->update_absence(id => $update_absence_id, absence_update => $update_absence_absence_update);


done_testing();
