=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::AttachmentVersionApi');

my $api = WWW::OpenAPIClient::AttachmentVersionApi->new();
isa_ok($api, 'WWW::OpenAPIClient::AttachmentVersionApi');

#
# create_attachment_version test
#
# uncomment below and update the test
#my $create_attachment_version_attachment_id = undef; # replace NULL with a proper value
#my $create_attachment_version_new_version_request = undef; # replace NULL with a proper value
#my $create_attachment_version_result = $api->create_attachment_version(attachment_id => $create_attachment_version_attachment_id, new_version_request => $create_attachment_version_new_version_request);

#
# list_attachment_versions test
#
# uncomment below and update the test
#my $list_attachment_versions_attachment_id = undef; # replace NULL with a proper value
#my $list_attachment_versions_result = $api->list_attachment_versions(attachment_id => $list_attachment_versions_attachment_id);

#
# restore_attachment_version test
#
# uncomment below and update the test
#my $restore_attachment_version_attachment_id = undef; # replace NULL with a proper value
#my $restore_attachment_version_version_id = undef; # replace NULL with a proper value
#my $restore_attachment_version_result = $api->restore_attachment_version(attachment_id => $restore_attachment_version_attachment_id, version_id => $restore_attachment_version_version_id);


done_testing();
