=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::AuthApi');

my $api = WWW::OpenAPIClient::AuthApi->new();
isa_ok($api, 'WWW::OpenAPIClient::AuthApi');

#
# accept_invite test
#
# uncomment below and update the test
#my $accept_invite_accept_invite_request = undef; # replace NULL with a proper value
#my $accept_invite_result = $api->accept_invite(accept_invite_request => $accept_invite_accept_invite_request);

#
# forgot_password test
#
# uncomment below and update the test
#my $forgot_password_forgot_password_request = undef; # replace NULL with a proper value
#my $forgot_password_result = $api->forgot_password(forgot_password_request => $forgot_password_forgot_password_request);

#
# login test
#
# uncomment below and update the test
#my $login_login_request = undef; # replace NULL with a proper value
#my $login_result = $api->login(login_request => $login_login_request);

#
# logout test
#
# uncomment below and update the test
#my $logout_result = $api->logout();

#
# magic_link_login test
#
# uncomment below and update the test
#my $magic_link_login_magic_link_request = undef; # replace NULL with a proper value
#my $magic_link_login_result = $api->magic_link_login(magic_link_request => $magic_link_login_magic_link_request);

#
# magic_link_verify test
#
# uncomment below and update the test
#my $magic_link_verify_magic_link_verify_request = undef; # replace NULL with a proper value
#my $magic_link_verify_result = $api->magic_link_verify(magic_link_verify_request => $magic_link_verify_magic_link_verify_request);

#
# register test
#
# uncomment below and update the test
#my $register_register_request = undef; # replace NULL with a proper value
#my $register_result = $api->register(register_request => $register_register_request);

#
# reset_password test
#
# uncomment below and update the test
#my $reset_password_reset_password_request = undef; # replace NULL with a proper value
#my $reset_password_result = $api->reset_password(reset_password_request => $reset_password_reset_password_request);

#
# totp_enable test
#
# uncomment below and update the test
#my $totp_enable_totp_enable_request = undef; # replace NULL with a proper value
#my $totp_enable_result = $api->totp_enable(totp_enable_request => $totp_enable_totp_enable_request);

#
# totp_setup test
#
# uncomment below and update the test
#my $totp_setup_result = $api->totp_setup();

#
# verify_email test
#
# uncomment below and update the test
#my $verify_email_verify_email_request = undef; # replace NULL with a proper value
#my $verify_email_result = $api->verify_email(verify_email_request => $verify_email_verify_email_request);


done_testing();
