=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BillingApi');

my $api = WWW::OpenAPIClient::BillingApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BillingApi');

#
# get_plans test
#
# uncomment below and update the test
#my $get_plans_result = $api->get_plans();

#
# get_quota_api test
#
# uncomment below and update the test
#my $get_quota_api_result = $api->get_quota_api();

#
# get_subscription_api test
#
# uncomment below and update the test
#my $get_subscription_api_result = $api->get_subscription_api();

#
# get_usage_api test
#
# uncomment below and update the test
#my $get_usage_api_meter = undef; # replace NULL with a proper value
#my $get_usage_api_result = $api->get_usage_api(meter => $get_usage_api_meter);

#
# paddle_subscription_webhook test
#
# uncomment below and update the test
#my $paddle_subscription_webhook_result = $api->paddle_subscription_webhook();

#
# put_quota_api test
#
# uncomment below and update the test
#my $put_quota_api_quota_override = undef; # replace NULL with a proper value
#my $put_quota_api_result = $api->put_quota_api(quota_override => $put_quota_api_quota_override);


done_testing();
