=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BomApi');

my $api = WWW::OpenAPIClient::BomApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BomApi');

#
# create_bom test
#
# uncomment below and update the test
#my $create_bom_bom_create = undef; # replace NULL with a proper value
#my $create_bom_result = $api->create_bom(bom_create => $create_bom_bom_create);

#
# delete_bom test
#
# uncomment below and update the test
#my $delete_bom_bom_id = undef; # replace NULL with a proper value
#my $delete_bom_result = $api->delete_bom(bom_id => $delete_bom_bom_id);

#
# get_bom test
#
# uncomment below and update the test
#my $get_bom_bom_id = undef; # replace NULL with a proper value
#my $get_bom_result = $api->get_bom(bom_id => $get_bom_bom_id);

#
# list_boms test
#
# uncomment below and update the test
#my $list_boms_page = undef; # replace NULL with a proper value
#my $list_boms_page_size = undef; # replace NULL with a proper value
#my $list_boms_search = undef; # replace NULL with a proper value
#my $list_boms_product_id = undef; # replace NULL with a proper value
#my $list_boms_result = $api->list_boms(page => $list_boms_page, page_size => $list_boms_page_size, search => $list_boms_search, product_id => $list_boms_product_id);

#
# update_bom test
#
# uncomment below and update the test
#my $update_bom_bom_id = undef; # replace NULL with a proper value
#my $update_bom_bom_update = undef; # replace NULL with a proper value
#my $update_bom_result = $api->update_bom(bom_id => $update_bom_bom_id, bom_update => $update_bom_bom_update);


done_testing();
