=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BudgetsApi');

my $api = WWW::OpenAPIClient::BudgetsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BudgetsApi');

#
# budgets_api test
#
# uncomment below and update the test
#my $budgets_api_year = undef; # replace NULL with a proper value
#my $budgets_api_month = undef; # replace NULL with a proper value
#my $budgets_api_result = $api->budgets_api(year => $budgets_api_year, month => $budgets_api_month);

#
# upsert_budget_goal_api test
#
# uncomment below and update the test
#my $upsert_budget_goal_api_category = undef; # replace NULL with a proper value
#my $upsert_budget_goal_api_budget_goal_request = undef; # replace NULL with a proper value
#my $upsert_budget_goal_api_result = $api->upsert_budget_goal_api(category => $upsert_budget_goal_api_category, budget_goal_request => $upsert_budget_goal_api_budget_goal_request);


done_testing();
