=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ContactApi');

my $api = WWW::OpenAPIClient::ContactApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ContactApi');

#
# contact_schema test
#
# uncomment below and update the test
#my $contact_schema_result = $api->contact_schema();

#
# contact_timeline test
#
# uncomment below and update the test
#my $contact_timeline_contact_id = undef; # replace NULL with a proper value
#my $contact_timeline_result = $api->contact_timeline(contact_id => $contact_timeline_contact_id);

#
# create_contact test
#
# uncomment below and update the test
#my $create_contact_body = undef; # replace NULL with a proper value
#my $create_contact_result = $api->create_contact(body => $create_contact_body);

#
# delete_contact test
#
# uncomment below and update the test
#my $delete_contact_contact_id = undef; # replace NULL with a proper value
#my $delete_contact_result = $api->delete_contact(contact_id => $delete_contact_contact_id);

#
# get_contact test
#
# uncomment below and update the test
#my $get_contact_contact_id = undef; # replace NULL with a proper value
#my $get_contact_result = $api->get_contact(contact_id => $get_contact_contact_id);

#
# list_contacts test
#
# uncomment below and update the test
#my $list_contacts_page = undef; # replace NULL with a proper value
#my $list_contacts_page_size = undef; # replace NULL with a proper value
#my $list_contacts_search = undef; # replace NULL with a proper value
#my $list_contacts_contact_type = undef; # replace NULL with a proper value
#my $list_contacts_tag = undef; # replace NULL with a proper value
#my $list_contacts_result = $api->list_contacts(page => $list_contacts_page, page_size => $list_contacts_page_size, search => $list_contacts_search, contact_type => $list_contacts_contact_type, tag => $list_contacts_tag);

#
# sales_volume test
#
# uncomment below and update the test
#my $sales_volume_page = undef; # replace NULL with a proper value
#my $sales_volume_page_size = undef; # replace NULL with a proper value
#my $sales_volume_search = undef; # replace NULL with a proper value
#my $sales_volume_contact_type = undef; # replace NULL with a proper value
#my $sales_volume_tag = undef; # replace NULL with a proper value
#my $sales_volume_result = $api->sales_volume(page => $sales_volume_page, page_size => $sales_volume_page_size, search => $sales_volume_search, contact_type => $sales_volume_contact_type, tag => $sales_volume_tag);

#
# update_contact test
#
# uncomment below and update the test
#my $update_contact_contact_id = undef; # replace NULL with a proper value
#my $update_contact_body = undef; # replace NULL with a proper value
#my $update_contact_result = $api->update_contact(contact_id => $update_contact_contact_id, body => $update_contact_body);


done_testing();
