=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::CouponApi');

my $api = WWW::OpenAPIClient::CouponApi->new();
isa_ok($api, 'WWW::OpenAPIClient::CouponApi');

#
# coupon_restore test
#
# uncomment below and update the test
#my $coupon_restore_coupon_id = undef; # replace NULL with a proper value
#my $coupon_restore_result = $api->coupon_restore(coupon_id => $coupon_restore_coupon_id);

#
# create_coupon test
#
# uncomment below and update the test
#my $create_coupon_coupon_create = undef; # replace NULL with a proper value
#my $create_coupon_result = $api->create_coupon(coupon_create => $create_coupon_coupon_create);

#
# delete_coupon test
#
# uncomment below and update the test
#my $delete_coupon_coupon_id = undef; # replace NULL with a proper value
#my $delete_coupon_result = $api->delete_coupon(coupon_id => $delete_coupon_coupon_id);

#
# get_coupon test
#
# uncomment below and update the test
#my $get_coupon_coupon_id = undef; # replace NULL with a proper value
#my $get_coupon_result = $api->get_coupon(coupon_id => $get_coupon_coupon_id);

#
# list_coupons test
#
# uncomment below and update the test
#my $list_coupons_page = undef; # replace NULL with a proper value
#my $list_coupons_page_size = undef; # replace NULL with a proper value
#my $list_coupons_is_active = undef; # replace NULL with a proper value
#my $list_coupons_code = undef; # replace NULL with a proper value
#my $list_coupons_discount_type = undef; # replace NULL with a proper value
#my $list_coupons_result = $api->list_coupons(page => $list_coupons_page, page_size => $list_coupons_page_size, is_active => $list_coupons_is_active, code => $list_coupons_code, discount_type => $list_coupons_discount_type);

#
# update_coupon test
#
# uncomment below and update the test
#my $update_coupon_coupon_id = undef; # replace NULL with a proper value
#my $update_coupon_coupon_update = undef; # replace NULL with a proper value
#my $update_coupon_result = $api->update_coupon(coupon_id => $update_coupon_coupon_id, coupon_update => $update_coupon_coupon_update);


done_testing();
