=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::CustomerCommunicationApi');

my $api = WWW::OpenAPIClient::CustomerCommunicationApi->new();
isa_ok($api, 'WWW::OpenAPIClient::CustomerCommunicationApi');

#
# create_communication test
#
# uncomment below and update the test
#my $create_communication_customer_communication_create = undef; # replace NULL with a proper value
#my $create_communication_result = $api->create_communication(customer_communication_create => $create_communication_customer_communication_create);

#
# customercommunication_restore test
#
# uncomment below and update the test
#my $customercommunication_restore_communication_id = undef; # replace NULL with a proper value
#my $customercommunication_restore_result = $api->customercommunication_restore(communication_id => $customercommunication_restore_communication_id);

#
# delete_communication test
#
# uncomment below and update the test
#my $delete_communication_communication_id = undef; # replace NULL with a proper value
#my $delete_communication_result = $api->delete_communication(communication_id => $delete_communication_communication_id);

#
# get_communication test
#
# uncomment below and update the test
#my $get_communication_communication_id = undef; # replace NULL with a proper value
#my $get_communication_result = $api->get_communication(communication_id => $get_communication_communication_id);

#
# get_contact_history test
#
# uncomment below and update the test
#my $get_contact_history_contact_id = undef; # replace NULL with a proper value
#my $get_contact_history_result = $api->get_contact_history(contact_id => $get_contact_history_contact_id);

#
# list_communications test
#
# uncomment below and update the test
#my $list_communications_page = undef; # replace NULL with a proper value
#my $list_communications_page_size = undef; # replace NULL with a proper value
#my $list_communications_contact_id = undef; # replace NULL with a proper value
#my $list_communications_channel = undef; # replace NULL with a proper value
#my $list_communications_direction = undef; # replace NULL with a proper value
#my $list_communications_from = undef; # replace NULL with a proper value
#my $list_communications_to = undef; # replace NULL with a proper value
#my $list_communications_result = $api->list_communications(page => $list_communications_page, page_size => $list_communications_page_size, contact_id => $list_communications_contact_id, channel => $list_communications_channel, direction => $list_communications_direction, from => $list_communications_from, to => $list_communications_to);

#
# update_communication test
#
# uncomment below and update the test
#my $update_communication_communication_id = undef; # replace NULL with a proper value
#my $update_communication_customer_communication_update = undef; # replace NULL with a proper value
#my $update_communication_result = $api->update_communication(communication_id => $update_communication_communication_id, customer_communication_update => $update_communication_customer_communication_update);


done_testing();
