=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::DeclarationApi');

my $api = WWW::OpenAPIClient::DeclarationApi->new();
isa_ok($api, 'WWW::OpenAPIClient::DeclarationApi');

#
# create_declaration test
#
# uncomment below and update the test
#my $create_declaration_declaration_create = undef; # replace NULL with a proper value
#my $create_declaration_result = $api->create_declaration(declaration_create => $create_declaration_declaration_create);

#
# declaration_restore test
#
# uncomment below and update the test
#my $declaration_restore_id = undef; # replace NULL with a proper value
#my $declaration_restore_result = $api->declaration_restore(id => $declaration_restore_id);

#
# delete_declaration test
#
# uncomment below and update the test
#my $delete_declaration_id = undef; # replace NULL with a proper value
#my $delete_declaration_result = $api->delete_declaration(id => $delete_declaration_id);

#
# get_declaration test
#
# uncomment below and update the test
#my $get_declaration_id = undef; # replace NULL with a proper value
#my $get_declaration_result = $api->get_declaration(id => $get_declaration_id);

#
# get_declarations test
#
# uncomment below and update the test
#my $get_declarations_page = undef; # replace NULL with a proper value
#my $get_declarations_page_size = undef; # replace NULL with a proper value
#my $get_declarations_search = undef; # replace NULL with a proper value
#my $get_declarations_include_deleted = undef; # replace NULL with a proper value
#my $get_declarations_result = $api->get_declarations(page => $get_declarations_page, page_size => $get_declarations_page_size, search => $get_declarations_search, include_deleted => $get_declarations_include_deleted);

#
# update_declaration test
#
# uncomment below and update the test
#my $update_declaration_id = undef; # replace NULL with a proper value
#my $update_declaration_declaration_update = undef; # replace NULL with a proper value
#my $update_declaration_result = $api->update_declaration(id => $update_declaration_id, declaration_update => $update_declaration_declaration_update);


done_testing();
