=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ImportRunnerApi');

my $api = WWW::OpenAPIClient::ImportRunnerApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ImportRunnerApi');

#
# get_import_status test
#
# uncomment below and update the test
#my $get_import_status_job_id = undef; # replace NULL with a proper value
#my $get_import_status_result = $api->get_import_status(job_id => $get_import_status_job_id);

#
# start_import test
#
# uncomment below and update the test
#my $start_import_import_start_request = undef; # replace NULL with a proper value
#my $start_import_result = $api->start_import(import_start_request => $start_import_import_start_request);

#
# test_import_connection test
#
# uncomment below and update the test
#my $test_import_connection_import_test_request = undef; # replace NULL with a proper value
#my $test_import_connection_result = $api->test_import_connection(import_test_request => $test_import_connection_import_test_request);


done_testing();
