=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::InventoryCountApi');

my $api = WWW::OpenAPIClient::InventoryCountApi->new();
isa_ok($api, 'WWW::OpenAPIClient::InventoryCountApi');

#
# create_inventory_count test
#
# uncomment below and update the test
#my $create_inventory_count_inventory_count = undef; # replace NULL with a proper value
#my $create_inventory_count_result = $api->create_inventory_count(inventory_count => $create_inventory_count_inventory_count);

#
# delete_inventory_count test
#
# uncomment below and update the test
#my $delete_inventory_count_inventory_count_id = undef; # replace NULL with a proper value
#my $delete_inventory_count_result = $api->delete_inventory_count(inventory_count_id => $delete_inventory_count_inventory_count_id);

#
# generate_inventory_count test
#
# uncomment below and update the test
#my $generate_inventory_count_generate_count_request = undef; # replace NULL with a proper value
#my $generate_inventory_count_result = $api->generate_inventory_count(generate_count_request => $generate_inventory_count_generate_count_request);

#
# get_inventory_count test
#
# uncomment below and update the test
#my $get_inventory_count_inventory_count_id = undef; # replace NULL with a proper value
#my $get_inventory_count_result = $api->get_inventory_count(inventory_count_id => $get_inventory_count_inventory_count_id);

#
# list_inventory_counts test
#
# uncomment below and update the test
#my $list_inventory_counts_page = undef; # replace NULL with a proper value
#my $list_inventory_counts_page_size = undef; # replace NULL with a proper value
#my $list_inventory_counts_status = undef; # replace NULL with a proper value
#my $list_inventory_counts_warehouse_id = undef; # replace NULL with a proper value
#my $list_inventory_counts_result = $api->list_inventory_counts(page => $list_inventory_counts_page, page_size => $list_inventory_counts_page_size, status => $list_inventory_counts_status, warehouse_id => $list_inventory_counts_warehouse_id);

#
# update_inventory_count test
#
# uncomment below and update the test
#my $update_inventory_count_inventory_count_id = undef; # replace NULL with a proper value
#my $update_inventory_count_body = undef; # replace NULL with a proper value
#my $update_inventory_count_result = $api->update_inventory_count(inventory_count_id => $update_inventory_count_inventory_count_id, body => $update_inventory_count_body);

#
# update_inventory_count_status test
#
# uncomment below and update the test
#my $update_inventory_count_status_inventory_count_id = undef; # replace NULL with a proper value
#my $update_inventory_count_status_inventory_count_status_update = undef; # replace NULL with a proper value
#my $update_inventory_count_status_result = $api->update_inventory_count_status(inventory_count_id => $update_inventory_count_status_inventory_count_id, inventory_count_status_update => $update_inventory_count_status_inventory_count_status_update);


done_testing();
