=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MarketplaceApiApi');

my $api = WWW::OpenAPIClient::MarketplaceApiApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MarketplaceApiApi');

#
# create_connection_api test
#
# uncomment below and update the test
#my $create_connection_api_create_connection_request = undef; # replace NULL with a proper value
#my $create_connection_api_result = $api->create_connection_api(create_connection_request => $create_connection_api_create_connection_request);

#
# delete_connection_api test
#
# uncomment below and update the test
#my $delete_connection_api_connection_id = undef; # replace NULL with a proper value
#my $delete_connection_api_result = $api->delete_connection_api(connection_id => $delete_connection_api_connection_id);

#
# get_connection_api test
#
# uncomment below and update the test
#my $get_connection_api_connection_id = undef; # replace NULL with a proper value
#my $get_connection_api_result = $api->get_connection_api(connection_id => $get_connection_api_connection_id);

#
# get_sync_direction_api test
#
# uncomment below and update the test
#my $get_sync_direction_api_connection_id = undef; # replace NULL with a proper value
#my $get_sync_direction_api_result = $api->get_sync_direction_api(connection_id => $get_sync_direction_api_connection_id);

#
# get_sync_logs_api test
#
# uncomment below and update the test
#my $get_sync_logs_api_connection_id = undef; # replace NULL with a proper value
#my $get_sync_logs_api_result = $api->get_sync_logs_api(connection_id => $get_sync_logs_api_connection_id);

#
# list_connections_api test
#
# uncomment below and update the test
#my $list_connections_api_result = $api->list_connections_api();

#
# list_platforms_api test
#
# uncomment below and update the test
#my $list_platforms_api_result = $api->list_platforms_api();

#
# oauth_authorize_api test
#
# uncomment below and update the test
#my $oauth_authorize_api_o_auth_authorize_request = undef; # replace NULL with a proper value
#my $oauth_authorize_api_result = $api->oauth_authorize_api(o_auth_authorize_request => $oauth_authorize_api_o_auth_authorize_request);

#
# oauth_callback_api test
#
# uncomment below and update the test
#my $oauth_callback_api_o_auth_callback_request = undef; # replace NULL with a proper value
#my $oauth_callback_api_result = $api->oauth_callback_api(o_auth_callback_request => $oauth_callback_api_o_auth_callback_request);

#
# trigger_sync_api test
#
# uncomment below and update the test
#my $trigger_sync_api_connection_id = undef; # replace NULL with a proper value
#my $trigger_sync_api_sync_type = undef; # replace NULL with a proper value
#my $trigger_sync_api_direction = undef; # replace NULL with a proper value
#my $trigger_sync_api_result = $api->trigger_sync_api(connection_id => $trigger_sync_api_connection_id, sync_type => $trigger_sync_api_sync_type, direction => $trigger_sync_api_direction);

#
# update_connection_api test
#
# uncomment below and update the test
#my $update_connection_api_connection_id = undef; # replace NULL with a proper value
#my $update_connection_api_update_connection_request = undef; # replace NULL with a proper value
#my $update_connection_api_result = $api->update_connection_api(connection_id => $update_connection_api_connection_id, update_connection_request => $update_connection_api_update_connection_request);

#
# update_sync_direction_api test
#
# uncomment below and update the test
#my $update_sync_direction_api_connection_id = undef; # replace NULL with a proper value
#my $update_sync_direction_api_update_sync_direction_request = undef; # replace NULL with a proper value
#my $update_sync_direction_api_result = $api->update_sync_direction_api(connection_id => $update_sync_direction_api_connection_id, update_sync_direction_request => $update_sync_direction_api_update_sync_direction_request);

#
# webhook_receiver_api test
#
# uncomment below and update the test
#my $webhook_receiver_api_platform = undef; # replace NULL with a proper value
#my $webhook_receiver_api_connection_id = undef; # replace NULL with a proper value
#my $webhook_receiver_api_result = $api->webhook_receiver_api(platform => $webhook_receiver_api_platform, connection_id => $webhook_receiver_api_connection_id);


done_testing();
