=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::PaygapApi');

my $api = WWW::OpenAPIClient::PaygapApi->new();
isa_ok($api, 'WWW::OpenAPIClient::PaygapApi');

#
# paygap_auskunft_api test
#
# uncomment below and update the test
#my $paygap_auskunft_api_employee_id = undef; # replace NULL with a proper value
#my $paygap_auskunft_api_result = $api->paygap_auskunft_api(employee_id => $paygap_auskunft_api_employee_id);

#
# paygap_export_api test
#
# uncomment below and update the test
#my $paygap_export_api_result = $api->paygap_export_api();

#
# paygap_report_api test
#
# uncomment below and update the test
#my $paygap_report_api_result = $api->paygap_report_api();


done_testing();
