=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::PaymentGatewayApi');

my $api = WWW::OpenAPIClient::PaymentGatewayApi->new();
isa_ok($api, 'WWW::OpenAPIClient::PaymentGatewayApi');

#
# create_payment_gateway_api test
#
# uncomment below and update the test
#my $create_payment_gateway_api_body = undef; # replace NULL with a proper value
#my $create_payment_gateway_api_result = $api->create_payment_gateway_api(body => $create_payment_gateway_api_body);

#
# delete_payment_gateway_api test
#
# uncomment below and update the test
#my $delete_payment_gateway_api_gateway_id = undef; # replace NULL with a proper value
#my $delete_payment_gateway_api_result = $api->delete_payment_gateway_api(gateway_id => $delete_payment_gateway_api_gateway_id);

#
# list_payment_gateways_api test
#
# uncomment below and update the test
#my $list_payment_gateways_api_result = $api->list_payment_gateways_api();

#
# oauth_authorize_api test
#
# uncomment below and update the test
#my $oauth_authorize_api_gateway_o_auth_authorize_request = undef; # replace NULL with a proper value
#my $oauth_authorize_api_result = $api->oauth_authorize_api(gateway_o_auth_authorize_request => $oauth_authorize_api_gateway_o_auth_authorize_request);

#
# oauth_callback_api test
#
# uncomment below and update the test
#my $oauth_callback_api_gateway_o_auth_callback_request = undef; # replace NULL with a proper value
#my $oauth_callback_api_result = $api->oauth_callback_api(gateway_o_auth_callback_request => $oauth_callback_api_gateway_o_auth_callback_request);

#
# update_payment_gateway_api test
#
# uncomment below and update the test
#my $update_payment_gateway_api_gateway_id = undef; # replace NULL with a proper value
#my $update_payment_gateway_api_body = undef; # replace NULL with a proper value
#my $update_payment_gateway_api_result = $api->update_payment_gateway_api(gateway_id => $update_payment_gateway_api_gateway_id, body => $update_payment_gateway_api_body);


done_testing();
