=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::PayrollApi');

my $api = WWW::OpenAPIClient::PayrollApi->new();
isa_ok($api, 'WWW::OpenAPIClient::PayrollApi');

#
# payroll_approve test
#
# uncomment below and update the test
#my $payroll_approve_id = undef; # replace NULL with a proper value
#my $payroll_approve_result = $api->payroll_approve(id => $payroll_approve_id);

#
# payroll_autopay test
#
# uncomment below and update the test
#my $payroll_autopay_id = undef; # replace NULL with a proper value
#my $payroll_autopay_body = undef; # replace NULL with a proper value
#my $payroll_autopay_result = $api->payroll_autopay(id => $payroll_autopay_id, body => $payroll_autopay_body);

#
# payroll_calculate test
#
# uncomment below and update the test
#my $payroll_calculate_id = undef; # replace NULL with a proper value
#my $payroll_calculate_result = $api->payroll_calculate(id => $payroll_calculate_id);

#
# payroll_create test
#
# uncomment below and update the test
#my $payroll_create_payroll_create_payload = undef; # replace NULL with a proper value
#my $payroll_create_result = $api->payroll_create(payroll_create_payload => $payroll_create_payroll_create_payload);

#
# payroll_delete test
#
# uncomment below and update the test
#my $payroll_delete_id = undef; # replace NULL with a proper value
#my $payroll_delete_result = $api->payroll_delete(id => $payroll_delete_id);

#
# payroll_elster_export test
#
# uncomment below and update the test
#my $payroll_elster_export_id = undef; # replace NULL with a proper value
#my $payroll_elster_export_result = $api->payroll_elster_export(id => $payroll_elster_export_id);

#
# payroll_email test
#
# uncomment below and update the test
#my $payroll_email_id = undef; # replace NULL with a proper value
#my $payroll_email_result = $api->payroll_email(id => $payroll_email_id);

#
# payroll_entry_pdf test
#
# uncomment below and update the test
#my $payroll_entry_pdf_id = undef; # replace NULL with a proper value
#my $payroll_entry_pdf_entry_id = undef; # replace NULL with a proper value
#my $payroll_entry_pdf_result = $api->payroll_entry_pdf(id => $payroll_entry_pdf_id, entry_id => $payroll_entry_pdf_entry_id);

#
# payroll_get test
#
# uncomment below and update the test
#my $payroll_get_id = undef; # replace NULL with a proper value
#my $payroll_get_result = $api->payroll_get(id => $payroll_get_id);

#
# payroll_list test
#
# uncomment below and update the test
#my $payroll_list_year = undef; # replace NULL with a proper value
#my $payroll_list_status = undef; # replace NULL with a proper value
#my $payroll_list_result = $api->payroll_list(year => $payroll_list_year, status => $payroll_list_status);

#
# payroll_pay test
#
# uncomment below and update the test
#my $payroll_pay_id = undef; # replace NULL with a proper value
#my $payroll_pay_payroll_pay_payload = undef; # replace NULL with a proper value
#my $payroll_pay_result = $api->payroll_pay(id => $payroll_pay_id, payroll_pay_payload => $payroll_pay_payroll_pay_payload);

#
# payroll_pdf test
#
# uncomment below and update the test
#my $payroll_pdf_id = undef; # replace NULL with a proper value
#my $payroll_pdf_result = $api->payroll_pdf(id => $payroll_pdf_id);

#
# payroll_summary test
#
# uncomment below and update the test
#my $payroll_summary_year = undef; # replace NULL with a proper value
#my $payroll_summary_result = $api->payroll_summary(year => $payroll_summary_year);

#
# payroll_sv_meldungen test
#
# uncomment below and update the test
#my $payroll_sv_meldungen_id = undef; # replace NULL with a proper value
#my $payroll_sv_meldungen_result = $api->payroll_sv_meldungen(id => $payroll_sv_meldungen_id);


done_testing();
