=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::PostingCategoryApi');

my $api = WWW::OpenAPIClient::PostingCategoryApi->new();
isa_ok($api, 'WWW::OpenAPIClient::PostingCategoryApi');

#
# create_posting_category test
#
# uncomment below and update the test
#my $create_posting_category_body = undef; # replace NULL with a proper value
#my $create_posting_category_result = $api->create_posting_category(body => $create_posting_category_body);

#
# delete_posting_category test
#
# uncomment below and update the test
#my $delete_posting_category_category_id = undef; # replace NULL with a proper value
#my $delete_posting_category_result = $api->delete_posting_category(category_id => $delete_posting_category_category_id);

#
# list_posting_categories test
#
# uncomment below and update the test
#my $list_posting_categories_result = $api->list_posting_categories();

#
# seed_posting_categories test
#
# uncomment below and update the test
#my $seed_posting_categories_skr_version = undef; # replace NULL with a proper value
#my $seed_posting_categories_result = $api->seed_posting_categories(skr_version => $seed_posting_categories_skr_version);

#
# update_posting_category test
#
# uncomment below and update the test
#my $update_posting_category_category_id = undef; # replace NULL with a proper value
#my $update_posting_category_body = undef; # replace NULL with a proper value
#my $update_posting_category_result = $api->update_posting_category(category_id => $update_posting_category_category_id, body => $update_posting_category_body);


done_testing();
