=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ProductVariantApi');

my $api = WWW::OpenAPIClient::ProductVariantApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ProductVariantApi');

#
# create_product_variant test
#
# uncomment below and update the test
#my $create_product_variant_product_variant = undef; # replace NULL with a proper value
#my $create_product_variant_result = $api->create_product_variant(product_variant => $create_product_variant_product_variant);

#
# delete_product_variant test
#
# uncomment below and update the test
#my $delete_product_variant_variant_id = undef; # replace NULL with a proper value
#my $delete_product_variant_result = $api->delete_product_variant(variant_id => $delete_product_variant_variant_id);

#
# generate_product_variants test
#
# uncomment below and update the test
#my $generate_product_variants_generate_variants_request = undef; # replace NULL with a proper value
#my $generate_product_variants_result = $api->generate_product_variants(generate_variants_request => $generate_product_variants_generate_variants_request);

#
# get_product_variant test
#
# uncomment below and update the test
#my $get_product_variant_variant_id = undef; # replace NULL with a proper value
#my $get_product_variant_result = $api->get_product_variant(variant_id => $get_product_variant_variant_id);

#
# list_product_variants test
#
# uncomment below and update the test
#my $list_product_variants_page = undef; # replace NULL with a proper value
#my $list_product_variants_page_size = undef; # replace NULL with a proper value
#my $list_product_variants_product_id = undef; # replace NULL with a proper value
#my $list_product_variants_is_active = undef; # replace NULL with a proper value
#my $list_product_variants_result = $api->list_product_variants(page => $list_product_variants_page, page_size => $list_product_variants_page_size, product_id => $list_product_variants_product_id, is_active => $list_product_variants_is_active);

#
# update_product_variant test
#
# uncomment below and update the test
#my $update_product_variant_variant_id = undef; # replace NULL with a proper value
#my $update_product_variant_body = undef; # replace NULL with a proper value
#my $update_product_variant_result = $api->update_product_variant(variant_id => $update_product_variant_variant_id, body => $update_product_variant_body);


done_testing();
