=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ReturnOrderApi');

my $api = WWW::OpenAPIClient::ReturnOrderApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ReturnOrderApi');

#
# create_return_order test
#
# uncomment below and update the test
#my $create_return_order_return_order = undef; # replace NULL with a proper value
#my $create_return_order_result = $api->create_return_order(return_order => $create_return_order_return_order);

#
# delete_return_order test
#
# uncomment below and update the test
#my $delete_return_order_return_order_id = undef; # replace NULL with a proper value
#my $delete_return_order_result = $api->delete_return_order(return_order_id => $delete_return_order_return_order_id);

#
# get_return_order test
#
# uncomment below and update the test
#my $get_return_order_return_order_id = undef; # replace NULL with a proper value
#my $get_return_order_result = $api->get_return_order(return_order_id => $get_return_order_return_order_id);

#
# list_return_orders test
#
# uncomment below and update the test
#my $list_return_orders_page = undef; # replace NULL with a proper value
#my $list_return_orders_page_size = undef; # replace NULL with a proper value
#my $list_return_orders_status = undef; # replace NULL with a proper value
#my $list_return_orders_customer_name = undef; # replace NULL with a proper value
#my $list_return_orders_order_number = undef; # replace NULL with a proper value
#my $list_return_orders_result = $api->list_return_orders(page => $list_return_orders_page, page_size => $list_return_orders_page_size, status => $list_return_orders_status, customer_name => $list_return_orders_customer_name, order_number => $list_return_orders_order_number);

#
# return_logistics_queue test
#
# uncomment below and update the test
#my $return_logistics_queue_result = $api->return_logistics_queue();

#
# return_logistics_summary test
#
# uncomment below and update the test
#my $return_logistics_summary_result = $api->return_logistics_summary();

#
# update_return_order test
#
# uncomment below and update the test
#my $update_return_order_return_order_id = undef; # replace NULL with a proper value
#my $update_return_order_body = undef; # replace NULL with a proper value
#my $update_return_order_result = $api->update_return_order(return_order_id => $update_return_order_return_order_id, body => $update_return_order_body);

#
# update_return_order_status test
#
# uncomment below and update the test
#my $update_return_order_status_return_order_id = undef; # replace NULL with a proper value
#my $update_return_order_status_return_order_status_update = undef; # replace NULL with a proper value
#my $update_return_order_status_result = $api->update_return_order_status(return_order_id => $update_return_order_status_return_order_id, return_order_status_update => $update_return_order_status_return_order_status_update);


done_testing();
