=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ServiceJobApi');

my $api = WWW::OpenAPIClient::ServiceJobApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ServiceJobApi');

#
# create_service_job test
#
# uncomment below and update the test
#my $create_service_job_service_job_create = undef; # replace NULL with a proper value
#my $create_service_job_result = $api->create_service_job(service_job_create => $create_service_job_service_job_create);

#
# delete_service_job test
#
# uncomment below and update the test
#my $delete_service_job_id = undef; # replace NULL with a proper value
#my $delete_service_job_result = $api->delete_service_job(id => $delete_service_job_id);

#
# get_service_job test
#
# uncomment below and update the test
#my $get_service_job_id = undef; # replace NULL with a proper value
#my $get_service_job_result = $api->get_service_job(id => $get_service_job_id);

#
# get_service_jobs test
#
# uncomment below and update the test
#my $get_service_jobs_page = undef; # replace NULL with a proper value
#my $get_service_jobs_page_size = undef; # replace NULL with a proper value
#my $get_service_jobs_search = undef; # replace NULL with a proper value
#my $get_service_jobs_include_deleted = undef; # replace NULL with a proper value
#my $get_service_jobs_result = $api->get_service_jobs(page => $get_service_jobs_page, page_size => $get_service_jobs_page_size, search => $get_service_jobs_search, include_deleted => $get_service_jobs_include_deleted);

#
# update_service_job test
#
# uncomment below and update the test
#my $update_service_job_id = undef; # replace NULL with a proper value
#my $update_service_job_service_job_update = undef; # replace NULL with a proper value
#my $update_service_job_result = $api->update_service_job(id => $update_service_job_id, service_job_update => $update_service_job_service_job_update);


done_testing();
