=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ShareholderApi');

my $api = WWW::OpenAPIClient::ShareholderApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ShareholderApi');

#
# create_shareholder test
#
# uncomment below and update the test
#my $create_shareholder_shareholder_create = undef; # replace NULL with a proper value
#my $create_shareholder_result = $api->create_shareholder(shareholder_create => $create_shareholder_shareholder_create);

#
# delete_shareholder test
#
# uncomment below and update the test
#my $delete_shareholder_id = undef; # replace NULL with a proper value
#my $delete_shareholder_result = $api->delete_shareholder(id => $delete_shareholder_id);

#
# get_shareholder test
#
# uncomment below and update the test
#my $get_shareholder_id = undef; # replace NULL with a proper value
#my $get_shareholder_result = $api->get_shareholder(id => $get_shareholder_id);

#
# get_shareholders test
#
# uncomment below and update the test
#my $get_shareholders_page = undef; # replace NULL with a proper value
#my $get_shareholders_page_size = undef; # replace NULL with a proper value
#my $get_shareholders_search = undef; # replace NULL with a proper value
#my $get_shareholders_include_deleted = undef; # replace NULL with a proper value
#my $get_shareholders_result = $api->get_shareholders(page => $get_shareholders_page, page_size => $get_shareholders_page_size, search => $get_shareholders_search, include_deleted => $get_shareholders_include_deleted);

#
# update_shareholder test
#
# uncomment below and update the test
#my $update_shareholder_id = undef; # replace NULL with a proper value
#my $update_shareholder_shareholder_update = undef; # replace NULL with a proper value
#my $update_shareholder_result = $api->update_shareholder(id => $update_shareholder_id, shareholder_update => $update_shareholder_shareholder_update);


done_testing();
