=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ShipmentApi');

my $api = WWW::OpenAPIClient::ShipmentApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ShipmentApi');

#
# create_shipment test
#
# uncomment below and update the test
#my $create_shipment_shipment = undef; # replace NULL with a proper value
#my $create_shipment_result = $api->create_shipment(shipment => $create_shipment_shipment);

#
# create_shipment_from_order test
#
# uncomment below and update the test
#my $create_shipment_from_order_order_number = undef; # replace NULL with a proper value
#my $create_shipment_from_order_create_shipment_request = undef; # replace NULL with a proper value
#my $create_shipment_from_order_result = $api->create_shipment_from_order(order_number => $create_shipment_from_order_order_number, create_shipment_request => $create_shipment_from_order_create_shipment_request);

#
# delete_shipment test
#
# uncomment below and update the test
#my $delete_shipment_shipment_id = undef; # replace NULL with a proper value
#my $delete_shipment_result = $api->delete_shipment(shipment_id => $delete_shipment_shipment_id);

#
# get_shipment test
#
# uncomment below and update the test
#my $get_shipment_shipment_id = undef; # replace NULL with a proper value
#my $get_shipment_result = $api->get_shipment(shipment_id => $get_shipment_shipment_id);

#
# list_shipments test
#
# uncomment below and update the test
#my $list_shipments_page = undef; # replace NULL with a proper value
#my $list_shipments_page_size = undef; # replace NULL with a proper value
#my $list_shipments_search = undef; # replace NULL with a proper value
#my $list_shipments_include_deleted = undef; # replace NULL with a proper value
#my $list_shipments_result = $api->list_shipments(page => $list_shipments_page, page_size => $list_shipments_page_size, search => $list_shipments_search, include_deleted => $list_shipments_include_deleted);

#
# track_order_public test
#
# uncomment below and update the test
#my $track_order_public_track_order_request = undef; # replace NULL with a proper value
#my $track_order_public_result = $api->track_order_public(track_order_request => $track_order_public_track_order_request);

#
# track_shipment_api test
#
# uncomment below and update the test
#my $track_shipment_api_shipment_id = undef; # replace NULL with a proper value
#my $track_shipment_api_result = $api->track_shipment_api(shipment_id => $track_shipment_api_shipment_id);

#
# update_shipment_status test
#
# uncomment below and update the test
#my $update_shipment_status_shipment_id = undef; # replace NULL with a proper value
#my $update_shipment_status_shipment_status_update = undef; # replace NULL with a proper value
#my $update_shipment_status_result = $api->update_shipment_status(shipment_id => $update_shipment_status_shipment_id, shipment_status_update => $update_shipment_status_shipment_status_update);


done_testing();
