=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SilentPartnerApi');

my $api = WWW::OpenAPIClient::SilentPartnerApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SilentPartnerApi');

#
# create_silent_partner test
#
# uncomment below and update the test
#my $create_silent_partner_silent_partner_create = undef; # replace NULL with a proper value
#my $create_silent_partner_result = $api->create_silent_partner(silent_partner_create => $create_silent_partner_silent_partner_create);

#
# delete_silent_partner test
#
# uncomment below and update the test
#my $delete_silent_partner_id = undef; # replace NULL with a proper value
#my $delete_silent_partner_result = $api->delete_silent_partner(id => $delete_silent_partner_id);

#
# get_silent_partner test
#
# uncomment below and update the test
#my $get_silent_partner_id = undef; # replace NULL with a proper value
#my $get_silent_partner_result = $api->get_silent_partner(id => $get_silent_partner_id);

#
# get_silent_partners test
#
# uncomment below and update the test
#my $get_silent_partners_page = undef; # replace NULL with a proper value
#my $get_silent_partners_page_size = undef; # replace NULL with a proper value
#my $get_silent_partners_search = undef; # replace NULL with a proper value
#my $get_silent_partners_include_deleted = undef; # replace NULL with a proper value
#my $get_silent_partners_result = $api->get_silent_partners(page => $get_silent_partners_page, page_size => $get_silent_partners_page_size, search => $get_silent_partners_search, include_deleted => $get_silent_partners_include_deleted);

#
# update_silent_partner test
#
# uncomment below and update the test
#my $update_silent_partner_id = undef; # replace NULL with a proper value
#my $update_silent_partner_silent_partner_update = undef; # replace NULL with a proper value
#my $update_silent_partner_result = $api->update_silent_partner(id => $update_silent_partner_id, silent_partner_update => $update_silent_partner_silent_partner_update);


done_testing();
