=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SuitabilityApi');

my $api = WWW::OpenAPIClient::SuitabilityApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SuitabilityApi');

#
# shipping_suitability_api test
#
# uncomment below and update the test
#my $shipping_suitability_api_suitability_request = undef; # replace NULL with a proper value
#my $shipping_suitability_api_result = $api->shipping_suitability_api(suitability_request => $shipping_suitability_api_suitability_request);


done_testing();
