=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::SupportTicketApi');

my $api = WWW::OpenAPIClient::SupportTicketApi->new();
isa_ok($api, 'WWW::OpenAPIClient::SupportTicketApi');

#
# create_ticket_api test
#
# uncomment below and update the test
#my $create_ticket_api_create_ticket_request = undef; # replace NULL with a proper value
#my $create_ticket_api_result = $api->create_ticket_api(create_ticket_request => $create_ticket_api_create_ticket_request);

#
# delete_ticket_api test
#
# uncomment below and update the test
#my $delete_ticket_api_ticket_id = undef; # replace NULL with a proper value
#my $delete_ticket_api_result = $api->delete_ticket_api(ticket_id => $delete_ticket_api_ticket_id);

#
# get_ticket_api test
#
# uncomment below and update the test
#my $get_ticket_api_ticket_id = undef; # replace NULL with a proper value
#my $get_ticket_api_result = $api->get_ticket_api(ticket_id => $get_ticket_api_ticket_id);

#
# list_tickets_api test
#
# uncomment below and update the test
#my $list_tickets_api_status = undef; # replace NULL with a proper value
#my $list_tickets_api_priority = undef; # replace NULL with a proper value
#my $list_tickets_api_assigned_to = undef; # replace NULL with a proper value
#my $list_tickets_api_channel_type = undef; # replace NULL with a proper value
#my $list_tickets_api_customer_id = undef; # replace NULL with a proper value
#my $list_tickets_api_search = undef; # replace NULL with a proper value
#my $list_tickets_api_page = undef; # replace NULL with a proper value
#my $list_tickets_api_page_size = undef; # replace NULL with a proper value
#my $list_tickets_api_result = $api->list_tickets_api(status => $list_tickets_api_status, priority => $list_tickets_api_priority, assigned_to => $list_tickets_api_assigned_to, channel_type => $list_tickets_api_channel_type, customer_id => $list_tickets_api_customer_id, search => $list_tickets_api_search, page => $list_tickets_api_page, page_size => $list_tickets_api_page_size);

#
# update_ticket_api test
#
# uncomment below and update the test
#my $update_ticket_api_ticket_id = undef; # replace NULL with a proper value
#my $update_ticket_api_support_ticket_update = undef; # replace NULL with a proper value
#my $update_ticket_api_result = $api->update_ticket_api(ticket_id => $update_ticket_api_ticket_id, support_ticket_update => $update_ticket_api_support_ticket_update);


done_testing();
