=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::TrainingsApi');

my $api = WWW::OpenAPIClient::TrainingsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::TrainingsApi');

#
# get_my_trainings test
#
# uncomment below and update the test
#my $get_my_trainings_result = $api->get_my_trainings();

#
# get_training_content test
#
# uncomment below and update the test
#my $get_training_content_code = undef; # replace NULL with a proper value
#my $get_training_content_result = $api->get_training_content(code => $get_training_content_code);

#
# get_training_overview test
#
# uncomment below and update the test
#my $get_training_overview_result = $api->get_training_overview();

#
# submit_training_result test
#
# uncomment below and update the test
#my $submit_training_result_submit_result_dto = undef; # replace NULL with a proper value
#my $submit_training_result_result = $api->submit_training_result(submit_result_dto => $submit_training_result_submit_result_dto);


done_testing();
