=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::TrainingAssignmentApi');

my $api = WWW::OpenAPIClient::TrainingAssignmentApi->new();
isa_ok($api, 'WWW::OpenAPIClient::TrainingAssignmentApi');

#
# create_training_assignment test
#
# uncomment below and update the test
#my $create_training_assignment_training_assignment_create = undef; # replace NULL with a proper value
#my $create_training_assignment_result = $api->create_training_assignment(training_assignment_create => $create_training_assignment_training_assignment_create);

#
# delete_training_assignment test
#
# uncomment below and update the test
#my $delete_training_assignment_id = undef; # replace NULL with a proper value
#my $delete_training_assignment_result = $api->delete_training_assignment(id => $delete_training_assignment_id);

#
# get_training_assignment test
#
# uncomment below and update the test
#my $get_training_assignment_id = undef; # replace NULL with a proper value
#my $get_training_assignment_result = $api->get_training_assignment(id => $get_training_assignment_id);

#
# get_training_assignments test
#
# uncomment below and update the test
#my $get_training_assignments_page = undef; # replace NULL with a proper value
#my $get_training_assignments_page_size = undef; # replace NULL with a proper value
#my $get_training_assignments_search = undef; # replace NULL with a proper value
#my $get_training_assignments_include_deleted = undef; # replace NULL with a proper value
#my $get_training_assignments_result = $api->get_training_assignments(page => $get_training_assignments_page, page_size => $get_training_assignments_page_size, search => $get_training_assignments_search, include_deleted => $get_training_assignments_include_deleted);

#
# update_training_assignment test
#
# uncomment below and update the test
#my $update_training_assignment_id = undef; # replace NULL with a proper value
#my $update_training_assignment_training_assignment_update = undef; # replace NULL with a proper value
#my $update_training_assignment_result = $api->update_training_assignment(id => $update_training_assignment_id, training_assignment_update => $update_training_assignment_training_assignment_update);


done_testing();
