=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::UserApi');

my $api = WWW::OpenAPIClient::UserApi->new();
isa_ok($api, 'WWW::OpenAPIClient::UserApi');

#
# change_password test
#
# uncomment below and update the test
#my $change_password_change_password_request = undef; # replace NULL with a proper value
#my $change_password_result = $api->change_password(change_password_request => $change_password_change_password_request);

#
# create_team test
#
# uncomment below and update the test
#my $create_team_team_create = undef; # replace NULL with a proper value
#my $create_team_result = $api->create_team(team_create => $create_team_team_create);

#
# generate_api_key test
#
# uncomment below and update the test
#my $generate_api_key_result = $api->generate_api_key();

#
# invite_user test
#
# uncomment below and update the test
#my $invite_user_invite_request = undef; # replace NULL with a proper value
#my $invite_user_result = $api->invite_user(invite_request => $invite_user_invite_request);

#
# list_teams test
#
# uncomment below and update the test
#my $list_teams_result = $api->list_teams();

#
# remove_user_from_org test
#
# uncomment below and update the test
#my $remove_user_from_org_remove_user_request = undef; # replace NULL with a proper value
#my $remove_user_from_org_result = $api->remove_user_from_org(remove_user_request => $remove_user_from_org_remove_user_request);

#
# update_profile test
#
# uncomment below and update the test
#my $update_profile_update_profile_request = undef; # replace NULL with a proper value
#my $update_profile_result = $api->update_profile(update_profile_request => $update_profile_update_profile_request);

#
# user_profile test
#
# uncomment below and update the test
#my $user_profile_result = $api->user_profile();

#
# user_tenants test
#
# uncomment below and update the test
#my $user_tenants_result = $api->user_tenants();


done_testing();
