=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::WarehouseStockApi');

my $api = WWW::OpenAPIClient::WarehouseStockApi->new();
isa_ok($api, 'WWW::OpenAPIClient::WarehouseStockApi');

#
# create_warehouse_stock test
#
# uncomment below and update the test
#my $create_warehouse_stock_warehouse_id = undef; # replace NULL with a proper value
#my $create_warehouse_stock_stock_adjustment = undef; # replace NULL with a proper value
#my $create_warehouse_stock_result = $api->create_warehouse_stock(warehouse_id => $create_warehouse_stock_warehouse_id, stock_adjustment => $create_warehouse_stock_stock_adjustment);

#
# delete_warehouse_stock test
#
# uncomment below and update the test
#my $delete_warehouse_stock_warehouse_id = undef; # replace NULL with a proper value
#my $delete_warehouse_stock_product_id = undef; # replace NULL with a proper value
#my $delete_warehouse_stock_result = $api->delete_warehouse_stock(warehouse_id => $delete_warehouse_stock_warehouse_id, product_id => $delete_warehouse_stock_product_id);

#
# list_warehouse_stock test
#
# uncomment below and update the test
#my $list_warehouse_stock_warehouse_id = undef; # replace NULL with a proper value
#my $list_warehouse_stock_result = $api->list_warehouse_stock(warehouse_id => $list_warehouse_stock_warehouse_id);

#
# update_warehouse_stock test
#
# uncomment below and update the test
#my $update_warehouse_stock_warehouse_id = undef; # replace NULL with a proper value
#my $update_warehouse_stock_product_id = undef; # replace NULL with a proper value
#my $update_warehouse_stock_stock_adjustment = undef; # replace NULL with a proper value
#my $update_warehouse_stock_result = $api->update_warehouse_stock(warehouse_id => $update_warehouse_stock_warehouse_id, product_id => $update_warehouse_stock_product_id, stock_adjustment => $update_warehouse_stock_stock_adjustment);


done_testing();
