=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::WebhooksApi');

my $api = WWW::OpenAPIClient::WebhooksApi->new();
isa_ok($api, 'WWW::OpenAPIClient::WebhooksApi');

#
# create_subscription test
#
# uncomment below and update the test
#my $create_subscription_create_subscription_request = undef; # replace NULL with a proper value
#my $create_subscription_result = $api->create_subscription(create_subscription_request => $create_subscription_create_subscription_request);

#
# delete_subscription test
#
# uncomment below and update the test
#my $delete_subscription_subscription_id = undef; # replace NULL with a proper value
#my $delete_subscription_result = $api->delete_subscription(subscription_id => $delete_subscription_subscription_id);

#
# emit_api test
#
# uncomment below and update the test
#my $emit_api_emit_event_request = undef; # replace NULL with a proper value
#my $emit_api_result = $api->emit_api(emit_event_request => $emit_api_emit_event_request);

#
# list_event test
#
# uncomment below and update the test
#my $list_event_result = $api->list_event();

#
# list_subscriptions test
#
# uncomment below and update the test
#my $list_subscriptions_result = $api->list_subscriptions();

#
# update_subscription test
#
# uncomment below and update the test
#my $update_subscription_subscription_id = undef; # replace NULL with a proper value
#my $update_subscription_update_subscription_request = undef; # replace NULL with a proper value
#my $update_subscription_result = $api->update_subscription(subscription_id => $update_subscription_subscription_id, update_subscription_request => $update_subscription_update_subscription_request);


done_testing();
