=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::InvoiceLineItem;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'InvoiceLineItem',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'article_number' => {
        datatype => 'string',
        base_name => 'article_number',
        description => '',
        format => '',
        read_only => '',
            },
    'description' => {
        datatype => 'string',
        base_name => 'description',
        description => '',
        format => '',
        read_only => '',
            },
    'discount_amount' => {
        datatype => 'string',
        base_name => 'discount_amount',
        description => '',
        format => '',
        read_only => '',
            },
    'discount_percentage' => {
        datatype => 'string',
        base_name => 'discount_percentage',
        description => '',
        format => '',
        read_only => '',
            },
    'input_vat_deductible' => {
        datatype => 'boolean',
        base_name => 'input_vat_deductible',
        description => '',
        format => '',
        read_only => '',
            },
    'input_vat_rate' => {
        datatype => 'string',
        base_name => 'input_vat_rate',
        description => '',
        format => '',
        read_only => '',
            },
    'is_intra_community_acquisition' => {
        datatype => 'boolean',
        base_name => 'is_intra_community_acquisition',
        description => '',
        format => '',
        read_only => '',
            },
    'is_margin_25a' => {
        datatype => 'boolean',
        base_name => 'is_margin_25a',
        description => '',
        format => '',
        read_only => '',
            },
    'ledger_account' => {
        datatype => 'string',
        base_name => 'ledger_account',
        description => '',
        format => '',
        read_only => '',
            },
    'line_total' => {
        datatype => 'string',
        base_name => 'line_total',
        description => '',
        format => '',
        read_only => '',
            },
    'line_total_gross' => {
        datatype => 'string',
        base_name => 'line_total_gross',
        description => '',
        format => '',
        read_only => '',
            },
    'margin_25a_purchase_price' => {
        datatype => 'string',
        base_name => 'margin_25a_purchase_price',
        description => '',
        format => '',
        read_only => '',
            },
    'meter_point_id' => {
        datatype => 'string',
        base_name => 'meter_point_id',
        description => '',
        format => '',
        read_only => '',
            },
    'position' => {
        datatype => 'int',
        base_name => 'position',
        description => '',
        format => '',
        read_only => '',
            },
    'price_components' => {
        datatype => 'object',
        base_name => 'price_components',
        description => '',
        format => '',
        read_only => '',
            },
    'product_id' => {
        datatype => 'string',
        base_name => 'product_id',
        description => '',
        format => '',
        read_only => '',
            },
    'product_sku' => {
        datatype => 'string',
        base_name => 'product_sku',
        description => '',
        format => '',
        read_only => '',
            },
    'quantity' => {
        datatype => 'string',
        base_name => 'quantity',
        description => '',
        format => '',
        read_only => '',
            },
    'supplier_article_number' => {
        datatype => 'string',
        base_name => 'supplier_article_number',
        description => '',
        format => '',
        read_only => '',
            },
    'tax_rate' => {
        datatype => 'string',
        base_name => 'tax_rate',
        description => '',
        format => '',
        read_only => '',
            },
    'unit' => {
        datatype => 'object',
        base_name => 'unit',
        description => '',
        format => '',
        read_only => '',
            },
    'unit_price' => {
        datatype => 'string',
        base_name => 'unit_price',
        description => '',
        format => '',
        read_only => '',
            },
    'usage_data_id' => {
        datatype => 'string',
        base_name => 'usage_data_id',
        description => '',
        format => '',
        read_only => '',
            },
    'vat_rate_nominal' => {
        datatype => 'string',
        base_name => 'vat_rate_nominal',
        description => '',
        format => '',
        read_only => '',
            },
    'vat_special_case' => {
        datatype => 'string',
        base_name => 'vat_special_case',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'article_number' => 'string',
    'description' => 'string',
    'discount_amount' => 'string',
    'discount_percentage' => 'string',
    'input_vat_deductible' => 'boolean',
    'input_vat_rate' => 'string',
    'is_intra_community_acquisition' => 'boolean',
    'is_margin_25a' => 'boolean',
    'ledger_account' => 'string',
    'line_total' => 'string',
    'line_total_gross' => 'string',
    'margin_25a_purchase_price' => 'string',
    'meter_point_id' => 'string',
    'position' => 'int',
    'price_components' => 'object',
    'product_id' => 'string',
    'product_sku' => 'string',
    'quantity' => 'string',
    'supplier_article_number' => 'string',
    'tax_rate' => 'string',
    'unit' => 'object',
    'unit_price' => 'string',
    'usage_data_id' => 'string',
    'vat_rate_nominal' => 'string',
    'vat_special_case' => 'string'
} );

__PACKAGE__->attribute_map( {
    'article_number' => 'article_number',
    'description' => 'description',
    'discount_amount' => 'discount_amount',
    'discount_percentage' => 'discount_percentage',
    'input_vat_deductible' => 'input_vat_deductible',
    'input_vat_rate' => 'input_vat_rate',
    'is_intra_community_acquisition' => 'is_intra_community_acquisition',
    'is_margin_25a' => 'is_margin_25a',
    'ledger_account' => 'ledger_account',
    'line_total' => 'line_total',
    'line_total_gross' => 'line_total_gross',
    'margin_25a_purchase_price' => 'margin_25a_purchase_price',
    'meter_point_id' => 'meter_point_id',
    'position' => 'position',
    'price_components' => 'price_components',
    'product_id' => 'product_id',
    'product_sku' => 'product_sku',
    'quantity' => 'quantity',
    'supplier_article_number' => 'supplier_article_number',
    'tax_rate' => 'tax_rate',
    'unit' => 'unit',
    'unit_price' => 'unit_price',
    'usage_data_id' => 'usage_data_id',
    'vat_rate_nominal' => 'vat_rate_nominal',
    'vat_special_case' => 'vat_special_case'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
