=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::Product;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

SimpleBilly API

Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.

The version of the OpenAPI document: 0.1.0
Contact: support@simplebilly.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'Product',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'availability' => {
        datatype => 'string',
        base_name => 'availability',
        description => '',
        format => '',
        read_only => '',
            },
    'barcode' => {
        datatype => 'string',
        base_name => 'barcode',
        description => '',
        format => '',
        read_only => '',
            },
    'brand' => {
        datatype => 'string',
        base_name => 'brand',
        description => '',
        format => '',
        read_only => '',
            },
    'category_id' => {
        datatype => 'string',
        base_name => 'categoryId',
        description => '',
        format => '',
        read_only => '',
            },
    'condition' => {
        datatype => 'string',
        base_name => 'condition',
        description => '',
        format => '',
        read_only => '',
            },
    'default_ledger_account' => {
        datatype => 'string',
        base_name => 'defaultLedgerAccount',
        description => '',
        format => '',
        read_only => '',
            },
    'default_price' => {
        datatype => 'string',
        base_name => 'defaultPrice',
        description => '',
        format => '',
        read_only => '',
            },
    'default_price_formula_id' => {
        datatype => 'string',
        base_name => 'defaultPriceFormulaId',
        description => 'References the price formula entity.',
        format => '',
        read_only => '',
            },
    'default_tax_rate' => {
        datatype => 'string',
        base_name => 'defaultTaxRate',
        description => '',
        format => '',
        read_only => '',
            },
    'description' => {
        datatype => 'string',
        base_name => 'description',
        description => '',
        format => '',
        read_only => '',
            },
    'gtin' => {
        datatype => 'string',
        base_name => 'gtin',
        description => '',
        format => '',
        read_only => '',
            },
    'height' => {
        datatype => 'string',
        base_name => 'height',
        description => '',
        format => '',
        read_only => '',
            },
    'image_link' => {
        datatype => 'string',
        base_name => 'imageLink',
        description => '',
        format => '',
        read_only => '',
            },
    'images' => {
        datatype => 'object',
        base_name => 'images',
        description => '',
        format => '',
        read_only => '',
            },
    'is_taxable' => {
        datatype => 'boolean',
        base_name => 'isTaxable',
        description => '',
        format => '',
        read_only => '',
            },
    'length' => {
        datatype => 'string',
        base_name => 'length',
        description => '',
        format => '',
        read_only => '',
            },
    'link' => {
        datatype => 'string',
        base_name => 'link',
        description => '',
        format => '',
        read_only => '',
            },
    'max_stock' => {
        datatype => 'int',
        base_name => 'maxStock',
        description => 'Target stock level used by reorder proposals.',
        format => '',
        read_only => '',
            },
    'min_stock' => {
        datatype => 'int',
        base_name => 'minStock',
        description => 'Reorder point — when stock falls below this, a reorder is suggested.',
        format => '',
        read_only => '',
            },
    'mpn' => {
        datatype => 'string',
        base_name => 'mpn',
        description => '',
        format => '',
        read_only => '',
            },
    'name' => {
        datatype => 'string',
        base_name => 'name',
        description => '',
        format => '',
        read_only => '',
            },
    'package_height' => {
        datatype => 'string',
        base_name => 'packageHeight',
        description => '',
        format => '',
        read_only => '',
            },
    'package_length' => {
        datatype => 'string',
        base_name => 'packageLength',
        description => '',
        format => '',
        read_only => '',
            },
    'package_weight_unit' => {
        datatype => 'string',
        base_name => 'packageWeightUnit',
        description => '',
        format => '',
        read_only => '',
            },
    'package_weight_value' => {
        datatype => 'string',
        base_name => 'packageWeightValue',
        description => '',
        format => '',
        read_only => '',
            },
    'package_width' => {
        datatype => 'string',
        base_name => 'packageWidth',
        description => '',
        format => '',
        read_only => '',
            },
    'product_code' => {
        datatype => 'string',
        base_name => 'productCode',
        description => '',
        format => '',
        read_only => '',
            },
    'product_type' => {
        datatype => 'string',
        base_name => 'productType',
        description => '',
        format => '',
        read_only => '',
            },
    'purchase_price' => {
        datatype => 'string',
        base_name => 'purchasePrice',
        description => '',
        format => '',
        read_only => '',
            },
    'reorder_quantity' => {
        datatype => 'int',
        base_name => 'reorderQuantity',
        description => 'Suggested purchase quantity when a reorder proposal is created.',
        format => '',
        read_only => '',
            },
    'sale_price' => {
        datatype => 'string',
        base_name => 'salePrice',
        description => '',
        format => '',
        read_only => '',
            },
    'shipping_price' => {
        datatype => 'string',
        base_name => 'shippingPrice',
        description => '',
        format => '',
        read_only => '',
            },
    'shipping_requires_insurance' => {
        datatype => 'boolean',
        base_name => 'shippingRequiresInsurance',
        description => '',
        format => '',
        read_only => '',
            },
    'sku' => {
        datatype => 'string',
        base_name => 'sku',
        description => '',
        format => '',
        read_only => '',
            },
    'stock_quantity' => {
        datatype => 'int',
        base_name => 'stockQuantity',
        description => '',
        format => '',
        read_only => '',
            },
    'tags' => {
        datatype => 'object',
        base_name => 'tags',
        description => '',
        format => '',
        read_only => '',
            },
    'tax_price' => {
        datatype => 'string',
        base_name => 'taxPrice',
        description => '',
        format => '',
        read_only => '',
            },
    'track_batch' => {
        datatype => 'boolean',
        base_name => 'trackBatch',
        description => 'Whether this product requires batch (Chargennummer) tracking.',
        format => '',
        read_only => '',
            },
    'track_serial' => {
        datatype => 'boolean',
        base_name => 'trackSerial',
        description => 'Whether this product requires serial-number tracking.',
        format => '',
        read_only => '',
            },
    'unit' => {
        datatype => 'object',
        base_name => 'unit',
        description => '',
        format => '',
        read_only => '',
            },
    'weight_unit' => {
        datatype => 'string',
        base_name => 'weightUnit',
        description => '',
        format => '',
        read_only => '',
            },
    'weight_value' => {
        datatype => 'string',
        base_name => 'weightValue',
        description => '',
        format => '',
        read_only => '',
            },
    'width' => {
        datatype => 'string',
        base_name => 'width',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'availability' => 'string',
    'barcode' => 'string',
    'brand' => 'string',
    'category_id' => 'string',
    'condition' => 'string',
    'default_ledger_account' => 'string',
    'default_price' => 'string',
    'default_price_formula_id' => 'string',
    'default_tax_rate' => 'string',
    'description' => 'string',
    'gtin' => 'string',
    'height' => 'string',
    'image_link' => 'string',
    'images' => 'object',
    'is_taxable' => 'boolean',
    'length' => 'string',
    'link' => 'string',
    'max_stock' => 'int',
    'min_stock' => 'int',
    'mpn' => 'string',
    'name' => 'string',
    'package_height' => 'string',
    'package_length' => 'string',
    'package_weight_unit' => 'string',
    'package_weight_value' => 'string',
    'package_width' => 'string',
    'product_code' => 'string',
    'product_type' => 'string',
    'purchase_price' => 'string',
    'reorder_quantity' => 'int',
    'sale_price' => 'string',
    'shipping_price' => 'string',
    'shipping_requires_insurance' => 'boolean',
    'sku' => 'string',
    'stock_quantity' => 'int',
    'tags' => 'object',
    'tax_price' => 'string',
    'track_batch' => 'boolean',
    'track_serial' => 'boolean',
    'unit' => 'object',
    'weight_unit' => 'string',
    'weight_value' => 'string',
    'width' => 'string'
} );

__PACKAGE__->attribute_map( {
    'availability' => 'availability',
    'barcode' => 'barcode',
    'brand' => 'brand',
    'category_id' => 'categoryId',
    'condition' => 'condition',
    'default_ledger_account' => 'defaultLedgerAccount',
    'default_price' => 'defaultPrice',
    'default_price_formula_id' => 'defaultPriceFormulaId',
    'default_tax_rate' => 'defaultTaxRate',
    'description' => 'description',
    'gtin' => 'gtin',
    'height' => 'height',
    'image_link' => 'imageLink',
    'images' => 'images',
    'is_taxable' => 'isTaxable',
    'length' => 'length',
    'link' => 'link',
    'max_stock' => 'maxStock',
    'min_stock' => 'minStock',
    'mpn' => 'mpn',
    'name' => 'name',
    'package_height' => 'packageHeight',
    'package_length' => 'packageLength',
    'package_weight_unit' => 'packageWeightUnit',
    'package_weight_value' => 'packageWeightValue',
    'package_width' => 'packageWidth',
    'product_code' => 'productCode',
    'product_type' => 'productType',
    'purchase_price' => 'purchasePrice',
    'reorder_quantity' => 'reorderQuantity',
    'sale_price' => 'salePrice',
    'shipping_price' => 'shippingPrice',
    'shipping_requires_insurance' => 'shippingRequiresInsurance',
    'sku' => 'sku',
    'stock_quantity' => 'stockQuantity',
    'tags' => 'tags',
    'tax_price' => 'taxPrice',
    'track_batch' => 'trackBatch',
    'track_serial' => 'trackSerial',
    'unit' => 'unit',
    'weight_unit' => 'weightUnit',
    'weight_value' => 'weightValue',
    'width' => 'width'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
